### DISCUSSION TITLE
How to disable automaticaly "backup", when "mount" in progress

### DISCUSSION THREAD

**Discussion by ryszard-suchocki** [creativeprojects/resticprofile#116] [Q&A] [answered]
Hello,
I would like to ask more experienced `resticprofile` users, how did you solve the kind of issue of running mount/restore and scheduled backups. I will shortly describe my scenario to shed some light on my "issue". I run a few PC where one crucial role is virtualization (QEMU/KVM). I have a script that prepares VM to backup (`incr`, `diff`, `full`) which requires creating 3 different `profiles` (for an incremental - different schedule, and so on for diff, full) [maybe here is an issue, I don't know any way to schedule at a specified time, nearly the same profile but with different env. variables][(feature request, allow specify extra vars in scheduler section)]. Restic, `resticprofile` profile (many thanks to devs & community!), the script works well - the job is done as I expected. Recently I had to restore VM. I search backup with the tag "full", mount that snap, and start recovering the VM. Note: I have 3 different profiles that operate on the same source data. The lock mechanism is probably working well for a current profile (i.e with extension "full") that was used to mount the repository, but I can use 3 different profiles to mount the repo (same source, same destination, same key). The question is: how to prevent/prohibit (in an efficient way) running profiles that operate on the same source. The restoration procedure can take some time, and different profiles can start doing their job...

**Comment by creativeprojects** [comment]
It should be handled by restic automatically:

In your case I don't think it's even an issue because you upload a new snapshot to a restic repository while reading a different  snapshot.

In any case, if restic thinks it's going to do two conflicting operations at the same time, it will tell you the repository is locked and you won't be able to do it.

**Reply by ryszard-suchocki** [reply]
It seems to be an "issue" with my run-before action in the backup section. The action runs even when the repo is locked (as the repo can be mounted on-demand before backup).

**Reply by creativeprojects** [reply]
~In that case you can use a resticprofile lock (these are separate from restic locks and include all run-* commands)~


Wait no you're saying they're from different machines so that doesn't work 😢

**Reply by ryszard-suchocki** [reply]
Machine (host) is the same, but I need to use 3 different profiles, because I need to invoke same command with different args, at different schedule. 
`unifi-backup.sh -a backup -m incr MYVMNAME` @ Mon..Fri 8,12,16,20:00, `unifi-backup.sh -a backup -m diff MYVMNAME` Mon..Fri 22:00 etc.

**Reply by ryszard-suchocki** [reply]
```yaml
{{ $VM_NAME }}:
    inherit: template-KVM
    env:
    - backuplevel: "incr"
    repository: "{{ $NAS01_REPO }}/{{ $VM_NAME }}"
    password-file: "keys.d/{{ $VM_NAME }}.key"
    copy:
        repository: "{{ $NAS02_REPO }}/{{ $VM_NAME }}"
        password-file: "keys.d/{{ $VM_NAME}}.key"
    backup:
        source:
        - "/storage/kvm/instances/{{ $VM_NAME }}/"
        schedule:
        - "Mon..Fri 8,12,16,20:30"
        run-before:
        -
        - "{{ .ConfigDir }}/unifi-backup.sh -a backup -m $BACKUPLEVEL -d {{ $VM_NAME }}"
        run-after:
        -
        - {{ $RA_ACTION  }}
        tag:
        - kvm
        - {{ .Profile.Name }}
    run-after-fail:
    -
    - {{ $RAF_ACTION }}

{{ $VM_NAME }}-Diff:
    inherit: {{ $VM_NAME }}
    env:
    - backuplevel: "diff"
    backup:
        schedule:
        - "Mon..Fri 21:30"
        - "Sat 20:30"

{{ $VM_NAME }}-Full:
    inherit: {{ $VM_NAME }}
    env:
    - backuplevel: "full"
    backup:
        schedule:
        - "Mon,Wed,Fri 23:00"

```
