### DISCUSSION TITLE
S3 repo copy to another S3

### DISCUSSION THREAD

**Discussion by ryszard-suchocki** [creativeprojects/resticprofile#123] [Q&A]
Hello,
I want to copy the S3 repository to another S3 repository. Is there any way to pass second/different credentials (env AWS_*, "buckets" served by different providers)? 

Best regards,
Ryszard

**Comment by creativeprojects** [comment]
That's a good question, I haven't done it before.

There's no _easy way_ available on resticprofile but I suppose you can add all the environment variables in the `env` section with a `_2` in the end for the destination repository

I'm not using S3 but I suppose it would look similar to this config for Azure:

```yaml

profile:
    env:
        AZURE_ACCOUNT_NAME: "backup-storage1"
        AZURE_ACCOUNT_KEY: "account_key=="
        AZURE_ACCOUNT_NAME_2: "backup-storage2"
        AZURE_ACCOUNT_KEY_2: "account_key=="

    initialize: false
    password-file: key1
    repository: "azure:restic:/"
    copy:
        initialize: true
        initialize-copy-chunker-params: true
        password-file: key2
        repository: "azure:restic-copy:/"
```

That's something I'll keep in mind for the version 2 of the configuration file 👍🏻
