### DISCUSSION TITLE
Resticprofile specify compression level

### DISCUSSION THREAD

**Discussion by stefanroellin** [creativeprojects/resticprofile#145] [Q&A] [answered]
Since restic version 0.14.0, it is possible to specify a compression level. 
Is there a possibility to specify the compression level in a profile? I haven't found anything in the documentation.

**Comment by jkellerer** [comment, marked as answer]
resticprofile passes any additional arguments that are specified inside a profile to the restic binary. In addition it also allows to specify extra environment variables. This means there are in general 2 options to specify compression mode:

**Option 1** - environment:

```yaml
default:
  environment:
    RESTIC_COMPRESSION: auto
```

**Option 2** - additional argument in backup section:

```yaml
default:
  backup:
    compression: auto
```
