### DISCUSSION TITLE
Comment out profiles with templates

### DISCUSSION THREAD

**Discussion by http403** [creativeprojects/resticprofile#209] [Q&A] [answered]
In my configuration file, I have a few `sent-after` sections combined with templates that I use for testing/debug. I want to disable them in day-to-day usage so I comented them out, but it doesn't work. Templates are still rendered. I tried using `#`, `//`, and `{#` `#}` pair. All doesn't work. Any suggestions?

Here's part of my profile:
```jinja
{{ define "hook_discord" }}
method = "POST"
url = {{ template "discord_webhook_url" . }}
body-template = "templates/discord-webhook.json"
{{ end }}

{{ define "hook_discord_fail" }}
method = "POST"
url = {{ template "discord_webhook_url" . }}
body-template = "templates/discord-webhook-fail.json"
{{ end }}

# [base.backup.send-after]
# {{ template "hook_discord" . }}

# [[base.backup.send-after.headers]]
# {{ template "hook_header_json" . }}

[base.backup.send-after-fail]
{{ template "hook_discord_fail" . }}

[[base.backup.send-after-fail.headers]]
{{ template "hook_header_json" . }}
```

And here's the output from trace:
```toml
# [base.backup.send-after]
#
method = "POST"
url = "<hidden>"
body-template = "templates/discord-webhook.json"


# [[base.backup.send-after.headers]]
#
name = "Content-Type"
value = "application/json"


[base.backup.send-after-fail]

method = "POST"
url = "<hidden>"
body-template = "templates/discord-webhook-fail.json"


[[base.backup.send-after-fail.headers]]

name = "Content-Type"
value = "application/json"
```
