### DISCUSSION TITLE
One Timer for 2 Repositories (incl. forget & check)

### DISCUSSION THREAD

**Discussion by bauerbyter** [creativeprojects/resticprofile#246] [Q&A] [answered]
Hey,
love resticprofile, thanks for the work!

I am pretty new to all that, so thanks in advance.

I have a Server and want to make 2 backups with resticprofile (one is already working fine!) and I just want to say: 
"Start at 01:00 and backup these folders to RepoA and directly after that make a forget and a check. If you a finished with that do the same with RepoB"

At the Moment I just have this for one Repo (and its using 3 timer, wouldn't it be better to just have one and do it in sequence?):

```
default:
  lock: "/*****/resticprofile-profile-default.lock"
  force-inactive-lock: true
  initialize: true
  repository: "sftp:****"
  password-file: "password.key"
  status-file: "ynh_backup-status.json"

  # Backup command
  backup:
    run-finally:
      # Extract lines that don't start with "unchanged " from the log and write them to "backup.log" in the current directory
      - 'grep --invert-match -E "^unchanged\\s" {{ tempFile "ynh_backup.log" }} > ynh_backup.log'
    one-file-system: true                                   # Don't leave the file system via mount points
    source:
      - "/home/****.**"
      - "/root/"
      - "/home/****.backup"
      - "/home/***"
    schedule: "04:00"
    schedule-permission: system
    schedule-lock-wait: 10m
    schedule-log: '{{ tempFile "ynh_backup.log" }}'             # Create log file "backup.log" in temporary directory and delete it when resticprofile is done
    verbose: 2                                              # Write details about each processed file to the log

  # Retention policy command
  forget:
    keep-daily: 7
    keep-weekly: 4
    prune: false
    schedule: "02:00"
    schedule-permission: system
    schedule-lock-wait: 1h

  # Verify command
  check:
    schedule: "3:00"
    schedule-permission: system
    schedule-lock-wait: 1h
```

**Comment by bauerbyter** [comment]
Okay sorry for that, found the answer to backup->forget->check: https://github.com/creativeprojects/resticprofile/discussions/226
But not for 2 repos

**Comment by jkellerer** [comment, marked as answer]
Scheduling multiple backups with one timer is a work in progress, it is not ready yet but on the list of future enhancements: #146 

As you already found `check` and `retention` can be bound to `backup` (just putting it here for reference):

```yaml
default:
  ....

  # Backup command
  backup:
    check-after: true
    source: [...]
    schedule: "04:00"

  # Retention policy command
  retention:
    after-backup: true    # will default to true from v0.23
    keep-daily: 7
    keep-weekly: 4
```
