### DISCUSSION TITLE
Unknown command "rewrite" for "restic"

### DISCUSSION THREAD

**Discussion by Subzeero** [creativeprojects/resticprofile#395] [Q&A] [answered]
Hey, I'm facing an odd issue where I cannot run restic's `rewrite` command with resticprofile. Every other command I've used seems to work fine.

Take the following executions:
```
> resticprofile rewrite --exclude /mnt/storage/pbs/backup-store
2024/08/14 22:49:04 using configuration file: profiles.yaml
2024/08/14 22:49:04 profile 'default': starting 'rewrite'
unknown command "rewrite" for "restic"
2024/08/14 22:49:04 rewrite on profile 'default': exit status 1

> resticprofile -h rewrite

No help from restic for "rewrite"
```

I'm not too sure what I'm doing wrong here; I hope my eyes aren't deceiving me haha. Any help would be appreciated. Thanks.

My profiles.yaml:
```
version: "1"

default:
  repository: "s3:***"
  password-file: "pass.txt"

  run-after: 'curl ...'
  run-after-fail: 'curl ...'

  env:
    AWS_ACCESS_KEY_ID: "***"
    AWS_SECRET_ACCESS_KEY: "***"
    RCLONE_BWLIMIT: "6M:12M"

  backup:
    verbose: true
    source:
      - "/***"
      - "/***"
      - "/***"
  forget:
    keep-monthly: 6
    keep-yearly: 2
    keep-within: 30d
    prune: true
```

<details>
<summary>Version information:</summary>
<code>> restic version
restic 0.17.0 compiled with go1.22.5 on linux/amd64
> resticprofile version
resticprofile version 0.27.1 commit eb130039b794e944223c7192673ccb04814347ca
</code>
</details>
