### DISCUSSION TITLE
Loop with stdin

### DISCUSSION THREAD

**Discussion by jasperjorna** [creativeprojects/resticprofile#414] [Q&A]
Hi,

I'm currently in the process of converting bash scripts to resticprofile. In my scripted version I'm currently looping through all existing MySQL databases and back them up via Restic with stdin. I know resticprofile has support for stdin, but can it also be used with a loop?

```sh
databases=`$MYSQL -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|sys)"`

for db in $databases; do
  mysqldump --complete-insert --routines --triggers --single-transaction --no-tablespaces --databases $db | gzip | $RESTIC -r $REPO backup --stdin --stdin-filename $db.gz --tag $db
done
```

**Comment by creativeprojects** [comment]
### Quick answer:
~No~ see answer bellow

### Long answer
Right now the configuration doesn't have any concept of _loops_ and probably won't in the near future.
An interesting concept I could imagine here would be to generate **dynamic profiles** from variables.

Now, on my databases, I found out that using `stdin` could lock your table for a certain amount of time depending on the speed of your backup support. With the traditional country-side dialup connection we have in the UK it takes a few minutes to upload a table and the database is locked in a read-only transaction, which causes some issue with services I'm running at home.
So I dump the databases into temporary files before doing a backup of the temporary files. No more locking issues. You just need some spare space on a disk.

```yaml
mysql:
  backup:
    tag:
      - mysql
    run-before:
      - rm -f /tmp/mysqldumpall.sql
      - mysqldump --all-databases > /tmp/mysqldumpall.sql
    source:
      - /tmp/mysqldumpall.sql
    run-after:
      - rm -f /tmp/mysqldumpall.sql
    schedule: 'daily'

```

Sorry if it's not the answer you were looking for 😉

**Reply by creativeprojects** [reply]
I was speaking too quickly! Actually you can do dynamic profiles with templates, I never thought of it before 😆 

Look at this configuration using the templating feature:

```yaml

# {{ $databases := .Env.databases | split " " }}

version: "2"

global:
  initialize: true

groups:
  mysql:
    profiles:
# {{ range $db := $databases }}
      - stdin-{{ $db }}
# {{ end }}

profiles:
  base:
    description: "Read from stdin"
    repository: "/Volumes/RAMDisk/example"
    password-file: key

# {{ range $db := $databases }}
  stdin-{{ $db }}:
    inherit: base
    description: "Database {{ $db }}"
    backup:
      stdin-command: "mysqldump --complete-insert --routines --triggers --single-transaction --no-tablespaces --databases {{ $db }}"
      stdin-filename: "{{ $db }}.sql"
      tag:
        - "{{ $db }}"
# {{ end }}

```

For the example I'm using configuration `v2`, but it would work the same way on `v1`

You need to populate the environment variable `databases` before starting resticprofile. Something like that would work:

```
databases=`$MYSQL -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|sys)"` resticprofile backup@mysql
```

- each element in `databases` environment variable is creating a profile named `stdin-DBNAME`
- a group of profiles named `mysql` is generated with the list of profiles
- running a backup on the group will run all profiles one after another

Quite cool right?

**Reply by jasperjorna** [reply]
@creativeprojects 

That's a pretty interesting approach!

I managed to get a little proof of concept working based on your example, but I'm wondering if this would still play nicely when _other_ profiles are included like this:

```yaml
includes:
  - "profiles/*.yaml"
```

**Reply by creativeprojects** [reply]
Yes, as long as there's no clash on the profile names you should be good.
All includes are loaded and compiled at the same time.

Note that a variable declared in one file cannot be used in another file though (like `{{ $databases }}`)

**Reply by jasperjorna** [reply]
Hmm, I get an error with the following setup:

**profiles.yaml**
```yaml
version: "1"

includes:
  - "profiles/*.yaml"

base:
  initialize: true
  extended-status: true
  env-file: ".restic-env"
  password-file: "password.txt"
```

**profiles/database.yaml:**
```yaml
{{ $databases := .Env.databases | split "\n" }}

version: "1"

groups:
  database:
    profiles:
      {{ range $db := $databases }}
      - stdin-{{ $db }}
      {{ end }}

{{ range $db := $databases }}
stdin-{{ $db }}:
  inherit: base
  backup:
    repository: "${REPOSITORY}/database"
    tag:
      - "stdin-{{ $db }}"
{{ end }}
```

```bash
databases=`mysql -u root -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|sys)"` resticprofile backup@database
2024/10/07 22:12:05 using configuration file: profiles.yaml
2024/10/07 22:12:05 profile or group not found: "database"

Profiles available (name, sections, description):
  base:                  (n/a)
  stdin-bar:             (backup)
  stdin-foo:  (backup)
  stdin-mysql:           (backup)
  system:                (backup, forget, init, list, ls, snapshots)

2024/10/07 22:12:05 failed loading groups: 1 error(s) decoding:

* '[database][0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[profiles:[stdin-bar stdin-foo stdin-mysql]]'
```


**2024/10/07 22:12:05 profile or group not found: "database"**

Okay, but would that mean that I need to put the `groups` in `profiles.yaml` and but `{{ $databases := .Env.databases | split "\n" }}` in both `profiles.yaml` and `profiles/database.yaml`?

I'm trying to figure out a way to keep the other profiles intact, and basically have the logic for the database dumps in its own profile.

Awesome project, btw! Cheers.

**Reply by creativeprojects** [reply]
It's the group definition that is wrong for the version 1 of the configuration, it needs to be:

```yaml
{{ $databases := .Env.databases | split "\n" }}

version: "1"

groups:
  database:
      {{ range $db := $databases }}
      - stdin-{{ $db }}
      {{ end }}

{{ range $db := $databases }}
stdin-{{ $db }}:
  inherit: base
  backup:
    repository: "${REPOSITORY}/database"
    tag:
      - "stdin-{{ $db }}"
{{ end }}
```

`groups` are only a list of profiles in `v1`, with no other option attached to them.
