### DISCUSSION TITLE
Send status fle at end

### DISCUSSION THREAD

**Discussion by cocox** [creativeprojects/resticprofile#451] [Ideas]
It will be useful to post the status file at end to a URL for processing.

**Comment by creativeprojects** [comment]
How about sending the content of the status file to an environment variable that can be picked up in a `run-after` or `send-after` target?

```yaml
profile:
    inherit: default
    backup:
        send-after:
            body: "${STATUS_FILE}"
            method: POST
            url: https://healthcheck.example.org/status
```
