### DISCUSSION TITLE
How to configure retention periods for non-standard schedules?

### DISCUSSION THREAD

**Discussion by davidfraser** [creativeprojects/resticprofile#453] [Q&A]
How can retention periods via [keep-within](https://creativeprojects.github.io/resticprofile/reference/profile/forget/index.html) be set for schedules that aren't hourly, daily, weekly etc?

I have multiple schedules set for the same profile in `profiles.yaml`:
```yaml
  backup:
    schedule:
      - hourly
      - "*-*-* 0,4,8,12,16,20:00:00"
  retention:
    keep-within-hourly: "7d"
    keep-within-daily: "30d"
```

But I can't see how to set a longer retention period for the four-hourly backup. I think the [restic source code is here](https://github.com/restic/restic/blob/master/internal/restic/snapshot_policy.go#L271) and from a brief look it seems that it's doing some kind of comparison to the duration rather than an exact match, but that would mean only something longer than a day would get a different schedule...

Is this possible? 

PS I am appreciating resticprofile's ability to set up multiple schedules, especially with the mixins in the v2 config
