### DISCUSSION TITLE
Make a .Group.Name variable available in the profiles section

### DISCUSSION THREAD

**Discussion by remyzandwijk** [creativeprojects/resticprofile#457] [Ideas]
Hi there. First of all, I have been using Restic for a couple of years now and I wrote a (very feature-incomplete) Python wrapper around it. While thinking about a rewrite of that wrapper, I came across Restic Profile and it is exactly what I need. So, thanks for writing it!

As a newcomer, I am fiddling around with trying several configurations. One of the things that came to mind is "I could really use the `.Group.Name` variable to be available (in profiles)". The use case of the `.Group.Name` variable would be to load the repository name and key for example, depending on the name of the group.

For example, I have a couple of profiles which should end-up in two different repositories:

```
version "2"

groups:
  group-a:
    profiles:
      - shared-profile-1
      - shared-profile-2
  group-b:
    profiles:
      - shared-profile-1
      - shared-profile-2

profiles:
  shared-profile-1:
    repository-file: "{{ .ConfigDir }}/{{ .Group.Name }}.repo"
    password-file: "{{ .ConfigDir }}/{{ .Group.Name }}.key"

  ...
```

So, when running `resticprofile group-a.backup` for example, the _group-a.repo_ and _group-a.key_ files would be used. And when `resticprofile group-b.backup` would run, the _group-b.repo_ and _group-b.key_ files would be used. 

Would having the `.Group.Name` variable available make sense?

I was trying to accomplish the above by using templates and inherritance, but I just cannot see how to do it. A workaround would be to supply an environment variable on the command line when starting resticprofile, but where is the fun in that, right? And I wonder if that would work out with adding schedules.

My concrete questions are:
1. Feature request: could the `.Group.Name` variable be made available in the profiles section?
2. Is there an other way how I could accomplish what I want?
