### DISCUSSION TITLE
Vector (.dev) works great for "run-after" backup log shipping to centralised log-management/monitoring tools

### DISCUSSION THREAD

**Discussion by 2q2code** [creativeprojects/resticprofile#458] [General]
I set this up for my mum's computer and laptop in addition to the suggestion of using prometheus pushgateway, because I wanted to see any stderr output as well, just to be sure I know of any issues in advance. This version is quite simple and doesn't have the remapping I am working on for the stderr lines, but I thought resticprofile users could really benefit from an example `vector.yaml`. If you call [vector.dev](https://vector.dev) in your resticprofile run-after action with something like:
```bash
vector -c vector.yaml < status_file.json
```
and (of course) have the resticprofile status file option on, you'll have the latest metrics and log lines from each backup shipped to your centralised log-monitoring tool. In the config example here, I use Grafana Loki:

```yaml
# vector.yaml
sources:
  status_file:
    type: stdin
    decoding:
      codec: json
sinks:
  loki:
    type: loki
    encoding:
      codec: "json"
    labels:
      host: "your_host_backing_up_here"
    inputs:
      - status_file
    endpoint: http://your_loki_hostname_here:3100
```

Vector is small, fast, and lightweight, plus it's available on `scoop` (for Windows hosts) as well as most linux package managers for most architectures. This way, you don't have to scrape anything, or install something like promtail and hope it scrubs over the logs before the user shuts the system down.
