### DISCUSSION TITLE
How do I run a 'copy' after a backup

### DISCUSSION THREAD

**Discussion by ilium007** [creativeprojects/resticprofile#513] [General]
I am a bit lost here. I have a backup running in the 'default' profile that puts data in an onsite Restic repo (for speed). I then have a 'copy' block defined in the 'default' profile to send snapshots to an offsite repo (Borgbase). What is the best way to have the copy run after a backup as the backup command does not have a 'after-backup' like 'retention' does.

The only way I can see to do this is run 'copy' on a standalone schedule based on time alone.

**Comment by ilium007** [comment]
Thinking about this some more... it could get messy. Retentions uses 'after-backup', how would a copy be defined? 'after-retention' ???

I am thinking it would need to look like:

```
retention:
  after: backup

copy:
  after: retention
```

**Comment by ilium007** [comment]
One of my configs below:

```
version: 1

global:
  priority: low
  default-command: snapshots
  initialize: true
  min-memory: 100
  scheduler: systemd
  #log: {{ tempFile "backup.log" }}
  restic-stale-lock-age: 2h

default:
  repository: "rest:http://xxxx:xxxx@datto01.sapling:8000/sapling-hosts/"
  password-file: master.key
  force-inactive-lock: true

  env:
    GOGC: 20

  backup:
    host: debian01.sapling
    verbose: true
    source:
      - /home
      - /root
      - /etc
      - /opt/microtech
    exclude-caches: true
    exclude:
      - /**/.git
      - /**/*.iso
      - /**/.cache/restic
      - /**/.cache
      - /**/#snapshot
      - /**/.vscode-server
      - /**/tmp
    tag:
      - resticprofile
    schedule: 03:00
    schedule-permission: system
    schedule-lock-wait: 2h

  retention:
    before-backup: false
    after-backup: true
    host: debian01.sapling
    keep-daily: 6
    keep-weekly: 3
    keep-monthly: 5
    #keep-last: 1
    keep-tag:
      - protected
    prune: true
  
  copy:
    repository: rest:https://xxx:xxx@xxxx.repo.borgbase.com
    password-file: master.key
    initialize: true
    initialize-copy-chunker-params: true
    host: debian01.sapling
    snapshot: latest

sapling-hosts:
  repository: rest:https://xxx:xxx@xxxx.repo.borgbase.com
  password-file: master.key

  forget:
    before-backup: false
    after-backup: true
    host: debian01.sapling
    keep-daily: 6
    keep-weekly: 3
    keep-monthly: 5
    keep-last: 1
    keep-tag:
      - protected
    prune: true
```
