### DISCUSSION TITLE
key-list

### DISCUSSION THREAD

**Discussion by ilium007** [creativeprojects/resticprofile#514] [Q&A]
Can someone pls tell me what `profile.key-list` does? https://creativeprojects.github.io/resticprofile/reference/profile/key-list/index.html

I have tested via:

```
default:
  key-list:
    send-after:
      URL: https://hc-ping.com/xxx
```

but it doesn't fire the https call after a `resticprofile -v key list`

`resticprofile -v key-list` results in:
```
unknown command "key-list" for "restic"
```

But:
```
default:
  key:
    send-after:
      URL: https://hc-ping.com/xxx
```
does work when sending `resticprofile -v key list` but will obviously fire the URL call for any `key` option.

So... what is https://creativeprojects.github.io/resticprofile/reference/profile/key-list/index.html used for? In my search through https://restic.readthedocs.io/en/latest/ there is no reference to `key-list`, only `key list`.
