### DISCUSSION TITLE
"Dynamic" groups

### DISCUSSION THREAD

**Discussion by qraynaud** [creativeprojects/resticprofile#522] [Ideas]
## My issue

I have a git repos containing all my personal server's applications described using the docker-compose syntax. I’d like to add each application backup config alongside those. So I made my profiles.yaml look like that:

```yaml
version: 2

global:
  initialize: true
  scheduler: crontab:-:/resticprofile/crontab

groups:
  daily:
    schedules:
      backup:
        at: '03:00'
        permission: user
  # ...

includes:
  - "/config/applications/*/*.backup.yaml"
```

And I’d like to be able to add to the `daily` group the profiles of apps that would make sense. Something like:

```yaml
profiles:
  my-app:
    # ...

groups:
  daily:
    profiles:
      - my-app
```

Obviously, this does not work because each app file replaces the profiles (like described in the documentation).

## Idea 1

Would it be possible to also support the append/prepend syntax in includes:
```yaml
profiles:
  my-app:
    # ...

groups:
  daily:
    profiles...: my-app
```

## Idea 2

Or to add a `groups` attribute in profiles that could be used in conjunction with `groups.profiles` to allow the link to be created wherever it makes more sense?
```yaml
profiles:
  my-app:
    # ...
    groups:
      - daily
```

## Idea 3

Or maybe it could be both #1 and #2?

## Ending word

Great project! Thanks a lot for the hard work!
