### ISSUE TITLE
Auto schedule of backup/retention/check

### ISSUE THREAD

**Issue by creativeprojects** [creativeprojects/resticprofile#10]
I'm getting closer to release a new version with a system to schedule backup automatically, via
- systemd on any supported platform
- launchd on macOS
- Task Scheduler on Windows

The idea is very simple, there are two new parameters in a configuration:

```yaml
self:
    inherit: default
    backup:
        source: "."
        schedule:
        - "Mon..Fri *:00,15,30,45" # every 15 minutes on weekdays
        - "Sat,Sun 0,12:*"         # twice a day on week-ends
        schedule-permission: user
    retention:
        schedule: "sun 3:30"
        schedule-permission: user
```

- `schedule` format is systemd calendar style
- `schedule-permission` is `user` or `system`

3 new internal commands will be available:
- schedule
- status
- unschedule

The schedule command will do everything for you: creating the configuration files, registering with systemd/launchd/task scheduler and loading it

The other commands are pretty self explanatory

So... I'm opening this issue for discussion:

- Does it look like it would cover most of the cases for scheduling backup/retention/check?
- Anything else you can think of?
