### ISSUE TITLE
Configuration merge issue

### ISSUE THREAD

**Issue by ryszard-suchocki** [creativeprojects/resticprofile#108]
Hello,
I would like to report an issue (maybe it is a feature) with the configuration merge process. My setup consists of a few directories and files. I.E. I have a dedicated folder for repositories config (repos.d) and profile templates (profiles.d). Repo config can inherit another repo config to allow easily choose whether I want to copy backed up data to repo1 or repo2. This works as expected. But when the template profile has a i.e backup section that defines run-before and run-after actions (list of actions) and I add run-before or run-after entries in a specialized profile (derived from template), my changes overload template action. I expect that I can extend configuration, but currently, there is only overload/shadow - whatever you call it. There is some workaround - in the derived profile define multiple empty list items and add desired action/hooks at the end.

| template 	| derived 	|
|---	|---	|
| backup:<br>  run-before:<br>    - action1<br>    - action2 	| backup:<br>  run-before:<br>    - action3<br>    - action4 	|

results invoking the action3 and action4 only (no action1 or action2)

| template 	| derived 	|
|---	|---	|
| backup:<br>  run-before:<br>    - action1<br>    - action2 	| backup:<br>  run-before:<br>    -<br>    -<br>    - action3<br>    - action4 	|

results invoking action1, action2, action3, action4.

**Comment by jkellerer** [comment]
@ryszard-suchocki , thanks for reporting this problem. 

The intended implementation is:
* Inheriting from another profile: Base profile defines defaults that can be overridden. No merging takes place on individual parameters (e.g. lists are replaced).
* Defining the same profile in multiple includes: Profiles are partially defined in multiple files and are fully merged together. List items should append to each other (within the same profile only).

Can reproduce the problem.

**Comment by ryszard-suchocki** [comment]
Maybe some kind of switch, that will allow choosing whether to overload or merge? I mean such change is somewhat breaking change.

**Comment by creativeprojects** [comment]
> Maybe some kind of switch, that will allow choosing whether to overload or merge? I mean such change is somewhat breaking change.

That's right, maybe some users are relying on this bug, or tweaked their configuration to make it work with it.

Now, would it be better to have an opt-in or an opt-out switch?

**Comment by jkellerer** [comment]
I’d keep the bug in version 1 config (the default when no version is specified) if it is caused by inheritance. 

Includes always merge since this is required to allow partial config definition in multiple files but this happens prior to inheritance processing. If the bug is caused by this (in viper lib as this is doing it) then it must be fixed. 

In version 2 config we could define a syntax to add to parameters (e.g. property+=[…]) then a base can be defined and derived profiles can extend lists if needed.

**Comment by jkellerer** [comment]
The additional callable config templates #115 in ConfigV2 may provide a way to append to list items while #108 will ensure that lists are no longer merged in an unintentional way.

**Comment by ryszard-suchocki** [comment]
Let me test before close ;)

**Comment by creativeprojects** [comment]
That was automatically closed when merging the PR

**Comment by ryszard-suchocki** [comment]
I tested some the new functionality (resticprofile version 0.18.0-dev commit ""). The new markup "..." works OK.Config v2 changes a lot about how to use resticprofile. Unfortunately, there is no option to append or replace items to the inherited "list" (mixins append works OK!). Please have a look on my config.

Template:

```
version: 2
mixins:
  kvm-backup:
    default-vars:
      VM: "CHANGE_ME"
      LEVEL: "incr"
      SCHEDULE: "Mon..Fri 8,12,16:00"
    backup:
      run-before...: 
      - '{{ .ConfigDir }}/misc.d/unifi-backup.sh -a backup -m $LEVEL $VM'
      schedule...: 
      - $SCHEDULE
      source...:
      - /storage/kvm/instances/$VM
      tag...:
      - kvm
      - $LEVEL
      - $VM
    retention:
      tag:
      - kvm
      - $LEVEL
      - $VM
    env...:
    - backup_level: $LEVEL
    - domain: $VM
```
Derived config

```
{{ $DOMAIN := "MY_VM_NAME"}}
version: 2
profiles:
  {{ $DOMAIN }}:
    use:
    - name: global-defaults
    # notifiers
    - name: notify-telegram
    - name: notify-goalert
    # pre-backup
    - name: kvm-backup
      VM: "{{ $DOMAIN }}"
      SCHEDULE: "Mon..Fri 8,12,16:15"
      LEVEL: "incr"
    # retention
    - name: std-retention
    # repository
    - name: repo-nas01
      DISTINCT: "{{ $DOMAIN }}"
    # replica
    copy:
      use:
      - name: repo-nas02
        DISTINCT: "{{ $DOMAIN }}"

  
  {{ $DOMAIN }}-Diff:
    inherit: {{ $DOMAIN }}
    use:
    - name: kvm-backup
      VM: "{{ $DOMAIN }}"
      SCHEDULE: "Fri 20:00"
      LEVEL: "diff"
    backup:
      tag:
      - newtag # NO REPLACE, NO APPEND - M.I.A.
      - newertag # M.I.A.
```
Result (produced by "show" command)

```
global:
    default-command:          snapshots
    restic-binary:           
    ... HERE IS MY GLOBAL CONFIG

profile MY_VM_NAME-Diff:
...
NOTHING INTERESTING
...

    env:
        backup_level:  diff
        domain:       MY_VM_NAME
        tmp:           /tmp

    backup:
...
NOTHING INTERESTING
...
        tag:         kvm
                     diff
                     MY_VM_NAME

    retention:
...
NOTHING INTERESTING
...
        prune:         true
        tag:           kvm
                       diff
                       MY_VM_NAME

    copy:
...
NOTHING INTERESTING
...

schedule MY_VM_NAME-Diff-backup:
    profiles:  MY_VM_NAME-Diff
    run:       backup
    schedule:  Fri 20:00
```
