### ISSUE TITLE
ConfigV2: Mixins & Includes

### ISSUE THREAD

**Issue by jkellerer** [creativeprojects/resticprofile#119]
The recent merged mixins feature has the ability to share pieces of configuration also when spread across includes like in the following example:

**profiles.yaml**

```yaml
version: 2
includes: '*.inc.yaml'

profiles:
  default:
    backup:
      use: exclude-hidden
```

**macos.inc.yaml**

```yaml
version: 2

profiles:
  default:
    backup:
      use: exclude-macos
```

**shared.inc.yaml**

```yaml
version: 2
mixins:
  exclude-hidden:
    exclude...: ['.*']
  exclude-macos:
    exclude...: ['.DS_Store']
```

At the moment, after processing all includes, the resulting default profile is:

```yaml
profiles:
  default:
    backup:
      exclude: ['.DS_Store']
```

The property `exclude` is not `['.*', '.DS_Store']` because `use` properties are overridden and only the last `use` really applies. For this example with a single property this would also happen when declaring `exclude` directly inside `profiles.yaml` and `macos.inc.yaml` but if different properties are specified mixins would also only apply the last `use` while includes would merge.

**Question**

Would it make sense to apply all `use` properties in order to have a similar merging behaviour as with includes (with the addition to be able to append to lists). This would require a change in that all occurrences of `use` need to be collected from every include and get applied after all includes have merged.
