### ISSUE TITLE
Interactive mode for mount / restore / stats / snapshots

### ISSUE THREAD

**Issue by ryszard-suchocki** [creativeprojects/resticprofile#128]
Hello,
I want to request enhancement that regards interactive mode for resticprofile when mount/restore/stats/snapshots are invoked. My motivation is quite simple - I have 2 repositories in my profile and I would like to choose whether I want to connect to the "main repo" or "copy repo". Currently, this requires manual file modification before any action. Would it be possible to read how many repository entries exist and if the profile has more than 1 display to choose which one should be used for mount/restore/stats/snapshots (commands without scheduler)? 

Best regards

**Comment by jkellerer** [comment]
Not sure if I get it correctly but shouldn't the following work:

```yaml
profile:
  repository: /main/repo
  ... all further config ...

profile-of-copy:
  inherit: profile
  repository: /copy/repo
```

```
resticprofile profile.mount /mnt/main-repo
resticprofile profile-of-copy.mount /mnt/copy-repo
```
