### ISSUE TITLE
[feature request] Condition section in profile

### ISSUE THREAD

**Issue by tj57** [creativeprojects/resticprofile#143]
What do you think about new condition section in the profile, and in it a list of conditions that must be met (logic AND) to proceed with each action, backup, prune etc. in this profile ?

You could call a script to check if the VPN tunnel or VM is working, etc.

```
profiles:
  photos:
     condition:
     - check_if_vpn_working.sh
     - check_if_vm_working.sh
```

It can be usefull in issue [135](https://github.com/creativeprojects/resticprofile/issues/135)
