### ISSUE TITLE
allow inherit in copy?

### ISSUE THREAD

**Issue by sedlund** [creativeprojects/resticprofile#147]
looking to do something like this:

```yaml
password:
  password-file: pass.txt

local:
  inherit: password
  repository: ~/backups/restic

remote:
  inherit: password
  repository: s3:https://minio.myserver.com/restic
  env:
    AWS_ACCESS_KEY_ID: 000
    AWS_SECRET_ACCESS_KEY: FFF

default:
  inherit: local
  backup:
    source: ~/
    exclude-file: excludes.txt
  copy:
    inherit: remote
```

or is there a better way to do this?

Thanks for the cool project!
