### ISSUE TITLE
Volume Name

### ISSUE THREAD

**Issue by FriedrichHSRT** [creativeprojects/resticprofile#156]
Hello, would be nice, if the windows version would be able to use volume names for target instead of driveletters (who can change).

cu
F. :-)

**Comment by jkellerer** [comment]
Would you mind running `resticprofile --dry-run your-profile.backup` and post the output in here so that we can see if the problem is related to passing of command line flags.

**Comment by FriedrichHSRT** [comment]
Hello, maybe a misunderstanding, I would like to have the feature to replace the drive letter with the volume name (because the drive letter can change). cu F. :-)

**Comment by jkellerer** [comment]
Ok, think I understand your request, you are referring to a solution like this:

```yaml
version: "2"

includes:
  - "volumes.conf"

global:
  initialize: true
  shell: powershell

profiles:  
  default:
    repository: "local:test-repo"
    password-file: "password.txt"
    run-before: 
      - echo "" | Out-File -Encoding ASCII "{{.ConfigDir}}/volumes.conf"
      - >-
        Get-WmiObject Win32_Volume
        | where Label
        | % { "[mixins.source_{0}]`r`n source='{1}{2}path'" -f ($_.Label -replace "\s", "_").ToLower(), ($_.Name -replace "\\", "/"), '$' }
        | Out-File -Encoding ASCII -Append "{{.ConfigDir}}/volumes.conf"

  system:
    inherit: default
    backup:
      use:
        - name: source_my_system_drive
          path: files/to/backup
      tag: my-tag
```

---

```
resticprofile.exe --quiet stats
scanning...
Stats in restore-size mode:
Snapshots processed:   0
         Total Size:   0 B

resticprofile.exe --dry-run system.backup
...
2022/12/27 16:34:46 dry-run: C:\Windows\system32\restic.exe backup --password-file password.txt --repo local:test-repo --tag my-tag C:/files/to/backup
...
```

(Assuming `C:\` is has a label of `My System Drive`)

---

Dynamically creating configuration from script is currently not supported explicitly, therefore an initial `stats` call (or similar) is required to build `volumes.conf`.

Translating volume labels to paths is a quite specific request. Maybe we can simplify using scripts inside the configuration to build values dynamically instead. The workaround from above should work in the meantime.
