### ISSUE TITLE
Backup Status is 2 if backup fails because of lock

### ISSUE THREAD

**Issue by tschoesi** [creativeprojects/resticprofile#162]
If the backup fails because of a lock that was left over from the process getting killed during a backup,
the statusfile (for prometheus) shows a status of `2` for `resticprofile_backup_status`.

I think it would be clearer if this was set to `0` or at the very least to `1`

**Comment by creativeprojects** [comment]
I had a look at it, and I think the problem is slightly different: A status file is *not generated* so prometheus only shows the latest one which was successful.

I think we should generate an empty file with a failed status (all the other metrics will be zero)

**Comment by tschoesi** [comment]
I am pretty sure that a status file was generated. Almost all metrics were set to 0 except for the duration metrics. 
Also the status file timestamp was updated to the time of the failed backup.

**Comment by tschoesi** [comment]
I checked again, and I think the problem is something else.
The status file gets created, but all the gauges are set to zero.
I have enabled `extended-status`

```yaml
default:
  repository: "/var/backups/restic"
  password-file: "key"
  prometheus-save-to-file: "prometheus/backup.prom"

  retention:
    after-backup: true
    prune: true
    keep-last: 5
    keep-weekly: 4
    keep-monthly: 3

  backup:
    extended-status: true
    one-file-system: true 
    source:
      - "/my/path"

```

Any ideas on what I'm doing wrong?
