### ISSUE TITLE
Issues sending a restic log to the Windows event view

### ISSUE THREAD

**Issue by Schroedingers-Cat** [creativeprojects/resticprofile#168]
I'm trying to send restic's output log to the windows event view via `run-after` using a custom powershell function. I'm invoking this via `run-after  = "powershell -command <my-powershell-command with params>"`.  

This was tricky to get working because:
- during `run-after` there's no variable available containing restic's log (as opposed to `run-after-fail` where `ERROR_MESSAGE` is available)
- the log file created via `schedule-log`
  -  is locked by resticprofile during the entire process
  - will never be cleaned for new runs of resticprofile

This means, to pipe the log into the Windows event view, I have no other choice but to use the log file, but that log will always contain the content of previous resticprofile runs, making it harder to read with every run.  

I was able to workaround this by adding a second action to the task generated by resticprofile which overwrites the existing log file with an empty one. The action consists of the command: `C:\Windows\System32\cmd.exe` with the parameter: `/C copy NUL  "C:\Path\To\profile-backup.log" /Y`.  

It would be great if this workaround wasn't necessary. I think this could be done by:
- the lock of log file could be freed at some point so that users could make this part of the commands they put into `run-after`
- the restic log could be made available via a variable

**Comment by jkellerer** [comment]
Besides other options (e.g. supporting windows event log), how about:
* On Windows the log file should be opened so that others can still read it (FILE_SHARE_READ or so, needs testing)
* We add a template function `{{ tempfile 'session.log' }}` that returns the path to a temporary file (the same file for the same name within the same run) that can be used in `schedule-log:` and also in `run-after/finally:` and that will be deleted when `resticprofile` ends.

**Comment by Schroedingers-Cat** [comment]
It sounds like all of your suggestions would remove the need for manual changes to the scheduled task, so they all sound good to me.

**Comment by jkellerer** [comment]
@Schroedingers-Cat , would you mind verifying if version 0.21.1 fixes your issue?

**Comment by Schroedingers-Cat** [comment]
@jkellerer thanks for letting me know!

This is how the relevant section of my profile looks:
```toml
  [userdata.backup]
    schedule-log = '{{ .TempDir }}\restic-userdata-backup.log'
    run-after  = "powershell -command Write-MessageEventFromFile -PathToLogFile '$Temp\\restic-userdata-backup.log'"
```

Scheduling that still concatenates the log for each run.  

I guess I'm supposed to create a log file with the new temp dir util func you mention in https://github.com/creativeprojects/resticprofile/pull/174? 
```
schedule-log: '{{ tempFile "rp-run.log" }}'
```

When I do that, I'm not sure how to access that log file in `run-after` within the context of `powershell --command`. I tried escaping the `"` with `\` but I'm still getting `cannot load configuration file: cannot compile template: __config:path\to\profiles.toml:24: unexpected "\\" in operand` when trying to schedule that profile. For reference, my profile would look like this;
```toml
  [userdata.backup]
    schedule-log = '{{ tempFile "rp-run.log" }}'
    run-after  = "powershell -command Write-MessageEventFromFile -PathToLogFile '{{ tempFile \"rp-run.log\" }}'"
```

I also tried getting rid of the `powershell --command` context by adding `powershell` as `shell` value to the global section. My hope was that this could simplify accessing the temporary log file but jobs scheduled like that fail to run with the following error:
```
+ c:\program files\tools\restic.exe backup --exclude-caches --exclude-f ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I have resticprofile in a subdirectory of `C:\Program Files`, which contains a whitespace and there seems to be an issue with the way the full path is placed into the task scheduler. I tried wrapping the path to resticprofile with `"` but that didn't help.  

What I'm trying to achieve is having a log of the current backup process (without the previous runs) available either as string or as text file during `run-after` and `run-finally` - without having to modify the generated scheduled task.

**Comment by jkellerer** [comment]
Thanks for the prompt response. Yes the behaviour of "schedule-log" did not change with regards to the content it creates. But the file is now accessible on Windows and as you mentioned we have support for a `tempFile` function in templates.

Have you tried it without escaping `{{ tempFile "rp-run.log" }}`?

Expressions like `{{ ... }}` are template syntax that is evaluated (and removed) prior to parsing the configuration as TOML, therefore the TOML parser only sees the temporary file path that is inserted (see also [templates](https://creativeprojects.github.io/resticprofile/configuration/templates/index.html)). I'm not sure what happens when the filename is escaped, I was actually assuming it would break. 

You can use `resticprofile --trace --dry-run userdata.backup` to see the resulting configuration when templates are applied and all shell commands that would be executed.

I had successfully tested it with:

````yaml
global:
  shell: powershell

default:
  backup:
    schedule-log: '{{ tempFile "test.log" }}'
    run-finally:
      - gc "{{ tempFile "test.log" }}" > ".\\resticprofile-last.log"
````

The part `gc "{{ tempFile "test.log" }}" >` is not escaped, since `{{ tempFile "test.log" }}` is replaced to a file path prior to parsing. It works the same with TOML, e.g.: `run-finally='gc "{{ tempFile "test.log" }}" > ".\\resticprofile-last.log"'`.

The `--trace` output of the config above is the following (note that we use forward slashes in temp-paths to avoid conflicts with escaping, `powershell` is fine with it):

````
 37:       schedule-log: 'C:/Users/jk/AppData/Local/Temp/resticprofile776175241/t/test.log'
 38:
 39:       run-finally:
 40:         - gc "C:/Users/jk/AppData/Local/Temp/resticprofile776175241/t/test.log" > ".\\resticprofile-last.log"
````

If it still breaks, could you share the output of `resticprofile --dry-run userdata.backup` ?

**Comment by Schroedingers-Cat** [comment]
> Expressions like `{{ ... }}` are template syntax that is evaluated (and removed) prior to parsing the configuration as TOML, therefore the TOML parser only sees the temporary file path that is inserted (see also [templates](https://creativeprojects.github.io/resticprofile/configuration/templates/index.html)). I'm not sure what happens when the filename is escaped, I was actually assuming it would break.

You're correct. Changing my profile to the following and ignoring the syntax highlighting issue raised by code editors fixes the issue:
```toml
  [userdata.backup]
    schedule-log = '{{ tempFile "restic-userdata-backup.log" }}'
    run-after  = "powershell -command Write-MessageEventFromFile -PathToLogFile '{{ tempFile "restic-userdata-backup.log" }}'"
```

I can confirm that setting up a profile like this allows users on Win to access the log of the current job during `run-after`. My custom powershell command sends the log of the current job with correct line breaks to the Windows event view. It's also nice that the temp file is cleaned up auatomatically after the job.  

Thank you so much for improving this!
