### ISSUE TITLE
Introduce a `run-with` option

### ISSUE THREAD

**Issue by damoclark** [creativeprojects/resticprofile#182]
Congrats on creating a really great companion for Restic.  :)

As a suggested improvement, it would be useful to be able to configure the use of utility commands for executing the restic binary, either within a restic profile, or even globally, allowing more customisable behaviour for specific operating systems and/or environments.

For example:

### Always run restic as another user
```yaml
default:
  run-with: sudo -u restic
```
Which would generate commands like:

```bash
sudo -u restic restic backup ...
sudo -u restic restic forget ...
etc
```
or
### Perform pull rather than push backups
```yaml
backup:
  run-with: "ssh hostname"
```
Which would generate the command:

```bash
ssh hostname restic backup ...
```
or
### For backups to local filesystem repository, set your primary unix group so all users of a group can read/write the repository files using restic
```yaml
backup:
  run-with: "sg - backups"
```
Which would generate the command:

```bash
sg - backups restic backup ...
```
or
### Use a [distributed lock manager](https://www.tiian.org/flom/) to execute the backups
```yaml
backup:
  run-with: "flom --lock-mode CW --"
```
Which would generate the command:

```bash
flom --lock-mode CW -- restic backup ...
```

Parameters to the utility commands could be altered through resticprofile variables and utility commands could be chained together.  For example:

### Use a distributed lock manager to execute different restic commands depending on lock semantics
```yaml
prune:
  run-with: "sudo -u {{ .sudo_user }} flom --resource-name '/{{ .Profile.Name }}' -l {{ .lock_mode }} --"
```
Which would generate the command:

```bash
sudo -u backups flom --resource-name '/myprofile' -l EX -- restic prune ...
```

Going a step further again, the full restic command itself, could be exposed as a built-in variable `{{ .Command }}`.  `.Command` could be an object that generates shell-escaped or quoted version of the command.

```yaml
backup:
  run-with: "/bin/sh time {{ .Command.quoted }} | tee -a .local/log/{{ .Profile.Name }}.log"
```
Which would generate the command:

```bash
/bin/sh time 'restic' 'backup' ... '/My Directory' | tee -a .local/log/myprofile.log
```

```yaml
backup:
  run-with: "/bin/sh time {{ .Command.quoted }} | tee -a .local/log/{{ .Profile.Name }}.log"
```
Which would generate the command:

```bash
/bin/sh time 'restic' 'backup' ... '/My Directory' | tee -a .local/log/myprofile.log
```

**Comment by jkellerer** [comment]
Hi @damoclark, 

Thanks a lot for the great feedback on possible use-cases when the restic commandline supported customisations. In fact we have a few cases (#153 - redirect to file/command & #69 - remote shell) that partially address this.

A custom shell environment declaration (e.g. with setup & teardown) and/or a commandline-template as you proposed might be quite useful. 

E.g. something like this (just a very quick draft):

```yaml
version: 2

environments:
  remote-shell:
    setup: 
      - "ssh {{ .Env.BACKUP_GATEWAY_HOST }}"
      - "ssh $TARGET_HOST"

  sudo-bash:
    shell: "bash"
    setup: 
      - "sudo -u {{ .Env.BACKUP_USER }} flom --resource-name '/{{ .Profile.Name }}' --"
    run: "(date ; $COMMNAND ; date)"

profiles:
  backup-remotes:
    backup:
      # default shell for backup
      shell:
        name: remote-shell
        foreach-vars:
          TARGET_HOST_FILE: "/hostlist.txt"

      run-before:
        
        - "echo running {{ .Profile.Name }} on $TARGET_HOST"
        
        - run: "echo running {{ .Profile.Name }} from $(hostname)"
          shell: "bash" # override shell to run locally
```

@creativeprojects , what do you think? 

Looks like it could not only cover this request but implement #69 pretty closely with moderate efforts. We'd need to check that most is covered and that it is maintainable. 

The way how variables can be used (including list [table?, matrix?]) will need a bit more planning. 

E.g. looping is something not directly related to this topic but useful. It may also be good to support it in the profile with environment variables rather than tying it to the `shell`:

```yaml
profiles:
  backup-remotes:
    run-foreach:
      name: "TARGET_HOST"
      delimiter: "\n"
      from-file: "/hostlist.txt"
```
