### ISSUE TITLE
resticprofile ignores `restic-binary` on Windows

### ISSUE THREAD

**Issue by Gaibhne** [creativeprojects/resticprofile#198]
resticprofile version 0.21.1
Windows 10

Config like this:

```yaml
# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

default:
  restic-binary: "C:\\Users\\me\\AppData\\Local\\Microsoft\\WinGet\\Links\\restic.exe"
```

Alternative, also doesn't work:

```yaml
# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

default:
  restic-binary: C:\Users\me\AppData\Local\Microsoft\WinGet\Links\restic.exe"
```

`resticprofile.exe show` results in:

```
2023/04/21 22:28:29 using configuration file: profiles.yaml
2023/04/21 22:28:29 cannot find restic: exec: "restic.exe": executable file not found in %PATH%
2023/04/21 22:28:29 you can specify the path of the restic binary in the global section of the configuration file (restic-binary)
```

Just to show that it works:

```
C:\restic>C:\Users\me\AppData\Local\Microsoft\WinGet\Links\restic.exe version
restic 0.15.1 compiled with go1.19.5 on windows/amd64

C:\restic>
```

**Comment by Gaibhne** [comment]
Addon: I have also tried with the non-link direct path, no difference.

**Comment by jkellerer** [comment]
Hi @Gaibhne , the setting `restic-binary` is part of the [global](https://creativeprojects.github.io/resticprofile/configuration/reference/index.html#section-global) section.

Could you try the following:

```yaml
# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"

global:
  restic-binary: C:\Users\me\AppData\Local\Microsoft\WinGet\Links\restic.exe

default:
  initialize: true
  repository: local:C:\test\repo
  password-file: C:\test\repo.key

  backup:
    source: C:\some\path\to\backup
```

... and if needed generate `repo.key` with:
```
resticprofile generate --random-key > C:\test\repo.key
```
