### ISSUE TITLE
Incorrect handling of multiple exclude files

### ISSUE THREAD

**Issue by Gaibhne** [creativeprojects/resticprofile#204]
A section like so is not handled correctly:

```yaml
    exclude-file:
      excludes\windows.exclude
      excludes\local.exclude
```

Expected outcome:

`restic.exe backup --exclude-file=excludes\windows.exclude --exclude-file=excludes\local.exclude [...]`

Actual outcome:

`restic.exe backup --exclude-file=excludes\windows.exclude excludes\local.exclude [...]`

Which will then interprete the second file name (and all following, presumably) as arguments to back up instead of excludes. Restic specifically allows for multiple exclude files, which makes sense as you can see from my example, which has generic excludes common to all Windows machines such as `C:\hiberfil.sys` as well as local excludes specific to that machine.

**Comment by jkellerer** [comment]
I'm assuming the example above is the actual YAML config snippet.

```yaml
default:
  backup:
    exclude-file:
      excludes\windows.exclude
      excludes\local.exclude
```

means `--exclude-file="excludes\windows.exclude excludes\local.exclude"` (since there are multiple ways to create [multiline strings](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines) in YAML, and this is the plain style that strips line breaks)

For multiple values on a single argument `resticprofile` expects list:

```yaml
default:
  backup:
    exclude-file:
      - excludes\windows.exclude
      - excludes\local.exclude
```

or

```yaml
default:
  backup:
    exclude-file: [excludes\windows.exclude, excludes\local.exclude]
```

Couldn't reproduce any issue here, so likely it should be fixed by converting using a list config. Please confirm.
