### ISSUE TITLE
Tags on schedules

### ISSUE THREAD

**Issue by d11ahirst** [creativeprojects/resticprofile#214]
Hi

This is more a question.

I have been looking at the documentation to see if there is a way of setting the tags based on the scheduled frequency of the backup i.e hourly or weekly etc.

Is this possible?

Thanks

**Comment by jkellerer** [comment]
At the moment not using a scripted / template approach since we don't have:
- Any environment variables set that would tell the profile run is scheduled (and with what settings)
- A way to dynamically set the environment from a shell hook (e.g. to set tags based on some evaluation done in the shell script)

What **is possible** is using **inheritance** (used `version=2` to have support for `__APPEND`):

```toml
version = "2"

[profiles.default]
  initialize = true
  repository = "{{ .Env.RESTIC_REPOSITORY }}"

  [profiles.default.backup]
    exclude = [ "~*", ".*" ]
    tag = [ "root" ]
    source = [ "/foldertobackup" ]
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-lock-wait = "10m"
    schedule-log = "backup.log"

[profiles.hourly]
  inherit = "default"
  
  [profiles.hourly.backup]
  tag__APPEND = ["hourly"]
  schedule = "hourly"

[profiles.daily]
  inherit = "default"
  
  [profiles.daily.backup]
  tag__APPEND = ["daily"]
  schedule = "daily"
```

```
➜ resticprofile hourly.show
...
profile hourly:
    backup:
        tag:      root
                  hourly
        source:   /foldertobackup
        exclude:  ~*
                  .*

schedule hourly-backup:
    profiles:    hourly
    run:         backup
    schedule:    hourly
    permission:  system
    log:         backup.log
    priority:    background
    lock-wait:   10m0s
```

```
➜ resticprofile show       
...
profile default:
    backup:
        tag:      root
        source:   /foldertobackup
        exclude:  ~*
                  .*
```
