### ISSUE TITLE
The first path from source gets filtered out on backup

### ISSUE THREAD

**Issue by SemperSolus0x3d** [creativeprojects/resticprofile#218]
Hello. I've run into an issue when the first path in the config is ignored when I create backups. Here's my minimal config to reproduce this bug:

```toml
version = "1"

[default]
password-command = 'echo password'
initialize = true
no-error-on-warning = true
repository = 'backup'

[default.backup]
source = [
    'test-folder',
    'test-folder-2'
]
```

Note the line `no-error-on-warning = true`. When I remove this line, everything works as expected.

## Steps to reproduce
1. Use the above config
2. Create 2 folders and name them "test-folder" and "test-folder-2"
3. Put some files into these folders
4. Run the command `resticprofile -v default.backup` and see that the "test-folder" is present in the "unfiltered command:" line, but is absent in the "starting command:" line:
![image](https://github.com/creativeprojects/resticprofile/assets/75125391/d2760058-27a4-4947-a27d-a0e303903ce4)
5. Run the command `resticprofile default.snapshots` and see that the snapshot is created without the "test-folder" path:
![image](https://github.com/creativeprojects/resticprofile/assets/75125391/1e56b619-9277-4f46-917f-8ce77906f883)

## Workarounds
- Don't use the `no-error-on-warning = true` option in the config
- Add the `-v` key to the end of the backup command. For example `resticprofile default.backup` then becomes `resticprofile default.backup -v`
- Add a dummy path to the config like this:
```toml
[default.backup]
source = [
    '', # dummy
    'test-folder',
    'test-folder-2'
]
```

## Versions
- restic 0.15.2 compiled with go1.20.3 on windows/amd64
- resticprofile version 0.22.0 commit ddf9debf89960db2c6139523ef6140a6538c5d27
