### ISSUE TITLE
Configuring a retention on a stdin profile applies the retention policy to the whole repository

### ISSUE THREAD

**Issue by Lucki** [creativeprojects/resticprofile#225]
I'm new to restic and maybe I'm interpreting the command output wrong. 
I have a few profiles in the configuration. Some normal path profiles and a stdin profile. One profile has no retention configured.

The retention output for the normal profile looked correct, listing all snapshots of that profile only and declaring the reasons to keep each one.
However, the output of the forget command from a stdin profile got me thinking:
`[…] keep 2 snapshots: […] Reasons: daily within 7d […]` is listed for a third profile, although that specific profile has no retention. In fact that command listed all profiles with the same retention policy.

The difference seems to be the `--path=…` command line flag which is missing for the profile using stdin.

Retention command after normal profile:
~~~ sh
starting command: /usr/bin/restic forget […] --path=/home/lucki --prune --repo=local:/run/media/lucki/backup/restic --verbose=1
~~~
Retention command after stdin profile which applies to all profiles including a profile without retention:
~~~ sh
starting command: /usr/bin/restic forget […] --prune --repo=local:/run/media/lucki/backup/restic --verbose=1
~~~

My uneducated guess is that the absence of the `--path=` flag will apply the retention policy to the whole repository regardless of other configured retention policies.

Reference example: https://creativeprojects.github.io/resticprofile/configuration/examples/index.html#use-stdin-in-configuration

<details>
<summary>My trimmed config</summary>

~~~ toml
version = "1"

[default]
    repository = "local:/run/media/lucki/backup/restic"
    verbose = true

[home]
    inherit = "default"

    [home.backup]
        source = [
            "/home/lucki",
        ]

    [home.retention]
        before-backup = false
        after-backup = true
        keep-within-yearly = "5y"
        keep-within-monthly = "1y"
        keep-within-weekly = "1m"
        keep-within-daily = "7d"
        prune = true

[gitea]
    inherit = "default"

    [gitea.backup]
        stdin-filename = "gitea.sql"
        stdin-command = [
            "pg_dump …",
        ]

    [gitea.retention]
        before-backup = false
        after-backup = true
        keep-within-yearly = "5y"
        keep-within-monthly = "1y"
        keep-within-weekly = "1m"
        keep-within-daily = "7d"
        prune = true

[third]
    inherit = "default"

    [third.backup]
        source = [
            "/mnt/third",
        ]

        # Notice *no* retention!
~~~

</details>

----
Bonus question:
While for includes it is made very clear that they can't nest this isn't specifically mentioned for inherited profiles. Is nesting possible for inherited profiles?

**Comment by jkellerer** [comment]
Retention automatically applies a `--path` filter (taken from backup `source`) to match only those snapshots in the repo that point to this path.

When using "stdin-filename" instead of a backup source, there is no `--path` to apply and "retention" (restic forget) will match any snapshot in the repository. 

Try using: 

```toml
[gitea]
    inherit = "default"

    [gitea.backup]
        stdin-filename = "gitea.sql"
        stdin-command = [
            "pg_dump …",
        ]
        tag = ["gitea", "pg_dump"]

    [gitea.retention]
        tag = true
        after-backup = true
        keep-within-yearly = "5y"
        keep-within-monthly = "1y"
        keep-within-weekly = "1m"
        keep-within-daily = "7d"
        prune = true
```

`retention` supports `tag=true` (implicit in version=2), `path=true` (implicit in version=1 & 2) and `host=true` to reuse `--path`, `--tag` and `--host` from `backup`.

To the bonus question: Inheritance can be nested it is not limited explicitly.
