### ISSUE TITLE
Nice in systemd unit is always 5

### ISSUE THREAD

**Issue by jee-r** [creativeprojects/resticprofile#229]
Hello 
I noticed that `nice` in global section is not correctly [passed](https://github.com/creativeprojects/resticprofile/blob/3476fbce1425f3368527c05a9130d511fe530139/systemd/generate.go#L31) to systemd unit template. 

for example with this config

```yaml
version: "1"
global:
  nice: 17
default:
  repository: "my_repo"
  password-file: "key"
  backup:
    exclude-file: "excludes"
    exclude-caches: true
    one-file-system: true
    tag:
      - "test"
    source:
      - "/tmp/"
    schedule: "*-*-* 12:15:00"
    schedule-permission: system
    schedule-priority: background
    schedule-lock-mode: default
    schedule-lock-wait: 15m30s
 ```
After running `schedule` the systemd unit file is 

```
cat /etc/systemd/system/resticprofile-backup@profile-default.service
[Unit]
Description=resticprofile backup for profile default in ./profiles.yaml

[Service]
Type=notify
WorkingDirectory=/tmp
ExecStart=/usr/local/bin/resticprofile --no-prio --no-ansi --config ./profiles.yaml --name default --lock-wait 15m30s backup
Nice=5
Environment="HOME=/root"
Environment="SUDO_USER=test"
```
Nice is set to 5 and not to 17 as expected

**Comment by creativeprojects** [comment]
This is right, I can see in `systemd` that nice is set to a predefined value:
https://github.com/creativeprojects/resticprofile/blob/3476fbce1425f3368527c05a9130d511fe530139/systemd/generate.go#L121

Thanks for the report 👍🏻

**Comment by flolilo** [comment]
Hello,
Just wanted to chime in that when starting resticprofile from the terminal with:

```
# leaving out definitely unrelated settings, i.e. paths
global:
  # neither this:
  priority: "idle"
  # nor this:
  nice: 19
  # ...nor both together change anything.

default:
  backup:
    verbose: 2
```
also will create restic instances with the default niceness.

- `resticprofile version`: resticprofile version 0.24.0 commit bcfaaa7cacfa7f88a94d5dc62ca69b2d89205d89
- `restic version`: restic 0.16.2 compiled with go1.21.3 on linux/amd64
