### ISSUE TITLE
Scheduling "retention" reads policy from "forget"

### ISSUE THREAD

**Issue by jkellerer** [creativeprojects/resticprofile#23]
### Finding

At the moment the following configuration schedules `forget` without any effect (at least with `systemd`):
```yaml
default:
  retention:
    prune: true
    keep-last: 14
    schedule: '@daily'
    schedule-permission: 'system'
```

The reason is that `retention` isn't a command but a configuration section that is mapped to `forget`. The schedule invokes `forget` which reads the retention config from the `forget` config section (that is what I'd expect when `forget` is scheduled). 
With the following workaround, it is possible to schedule `forget` (forget itself cannot be scheduled directly):
```yaml
default:
  forget:
    prune: true
    keep-last: 14
  retention:
    schedule: '@daily'
    schedule-permission: 'system'
```

### Suggestion

The idea to have `retention` policies defined with `backup` is great since it allows to have separate retention settings per tag & path. When called before or after backup and without `prune` (for large repos) it is also a fast operation. So this should not be changed, it is good as it is.

However, instead of artificially mapping `retention` to a scheduled `forget` command, I'd suggest to allow scheduling `forget` directly and remove the option to schedule `retention` (it is broken anyway).

See also #22 , when prune can be scheduled separately, then there are less use cases where scheduling `forget` (with or without prune) really makes sense, still I'd allow it as there may be cases where it is needed.
