### ISSUE TITLE
.Stdout in HTTP hook body template seems to always be empty

### ISSUE THREAD

**Issue by guahki** [creativeprojects/resticprofile#260]
First: thanks for this awesome tool helping to easily deploy restic!

I just tried to use ``.Stdout`` in the ``body-template`` as described [in the docs](https://creativeprojects.github.io/resticprofile/configuration/http_hooks/index.html#body-template) (using ``resticprofile`` in version 0.23.0). But it seems to always be empty, regardless of error state and output of before running commands.

Am I doing something wrong? Do you need to set some undocumented setting for it to work?

Despite not being familiar with Go I tried to find the place where this variable is set, but could not find it. I found the definition of the struct at https://github.com/creativeprojects/resticprofile/blob/61f60152dddc935231a7ccf4a25edf04992d1cdb/monitor/hook/context.go#L10 but despite extensive search could not find any place populating this struct value. Is it possible that it was forgotten to populate it in https://github.com/creativeprojects/resticprofile/pull/114? I find only two occurences of ``Stdout`` in the diff of this PR and one is the docs, the other the above mentioned definition.

**Comment by creativeprojects** [comment]
I think you're right, it looks like it got missed 😨

**Comment by guahki** [comment]
No problem. Unfortunatelly, I really do know nothing about Go, so I can't help by providing a PR, sorry.

Do you see any way of temporarily work around this by using the ``schedule-log`` setting and include the resulting file in the ``body-template``? I tried, but failed to find any method of including a plain file in the Go template language. Might be easy and I just missed it, as (as I said) I'm not familiar with Go at all.

And the long-term question: can you say, if you plan to include the ``.Stdout`` correctly? Can you give a (obviously very rough) estimate when this might happen? I would never nail you down on this, but just to get a feel, if you are working on it right now or it's far down on the priority list.

**Comment by jkellerer** [comment]
@guahki, I'll reference this case for #207 and look into it. Was a bit busy with other things lastly but will continue to work on the PR soon. 

So far we always tried to avoid redirecting stdout to not alter the default behaviour of `restic` (which does not display any progress when stdout is redirected). But with #207 we will be able to redirect more easily and capture the output so that it can be provided in `.Stdout`.

Regarding a workaround, how about:

```yaml
  {{ $body := tempFile "body-template-file" }}
  default:
    backup:
      schedule-log: '{{ tempFile "log-output" }}'

      run-finally: 
        - echo "Log for {{ .Profile.Name }} @ {{ .Hostname }}:" > '{{ $body }}'
        - echo "---------------------------------------------" >> '{{ $body }}'
        - cat '{{ tempFile "log-output" }}' >> '{{ $body }}'
        - echo "---------------------------------------------" >> '{{ $body }}'

      send-finally:
        - body-template: '{{ $body }}'
```

Regarding including files in templates. So far we do not provide such an extension. I had thought about it beforehand but had no use case that requires it. Maybe I can add an include function for raw includes in in go templates with one of the next releases.
