### ISSUE TITLE
Relative source path with glob starting with dash doesn't work 

### ISSUE THREAD

**Issue by zxcat** [creativeprojects/resticprofile#264]
Let have two profiles:
* 1st excluding paths starting with `-`,
* 2nd include only them.

Simplified sample (without `inherit`, `tags`, etc…), can be like:
```yaml
profiles:
  one:
    backup:
      exclude: '-*'
      source: '.'

  two:
    backup:
      source:
        - '-*'     # ignored
        - './-*'   # ignored
        - './-withoutGlob'  # only this source works
```

The problem is that with the following conditions:
1. relative path
2. uses glob
3. starting with dash

`resticprofile` passes empty sources to `restic` (checked with `--dry-run` option).
So users have to put explicit paths (`./-withoutGlob`), which makes config less maintainable.

**Comment by jkellerer** [comment]
@zxcat, that is in fact a bug thanks for the detailed report.

A workaround (until the bug is fixed) is to specify a base path for source:

```yaml
  two:
    backup:
      #source-base: /path/to/base
      source-base: '{{ .StartupDir | js }}'
      source:
        - '-*'              # works and no longer ignored
        - './-withoutGlob'  # also works
```
