### ISSUE TITLE
Question on Schedules in v2: How to schedule them (v0.23)? And some extra questions

### ISSUE THREAD

**Issue by arberg** [creativeprojects/resticprofile#265]
Hi, 

I really like the new v2 format, and resticprofile in general. I see Fred and jkellerer are working actively on schedule-v2, so possibly I just need patience. (?) But probably its just that I cannot find the right way to trigger the command, hence this question. I'll probably end up scheduling it manually until the format stabilized, but I figured it doesn't hurt asking.

#### Question

My question: Is it possible in v0.23.0 to use the schedule section? If so, how do I ask resticprofile to schedule it? I have schedules working when I add them to the profile, but not when adding to the new schedules root-section.

#### What I'm trying to achieve:
I would like to have one task that runs the backups sequentially to avoid getting into unnecessary self-lock issues (with the forget) and to avoid spamming HDD with concurrent requests from the same PC. So I want all my 'daily' backups to run sequentially, and all my `hourly` backups to run sequentially (though I have only one of those at the momement). So two TaskScheduler tasks, 1 daily and 1 hourly. The v2-schedules seem perfect for this (to avoid my own custom *.ps1 scripts and managing tasks myself directly).

#### Commands

Commands that work, but the schedule commands ONLY work when i have `schedule` subsection under `root.backup`. If I remove that schedule section in the believe that my root schedules section should work, it does not work
- `.\resticprofile.exe -c test.yaml maindrives.backup`
- `.\resticprofile.exe -c test.yaml maindrives.schedule`
  - This will schedule individual 
- `.\resticprofile.exe -c test.yaml schedule --all`
  - This will schedule all including my root
  
Commands that does not work:  
- `.\resticprofile.exe -c test.yaml maindrives.schedule`

#### Configuration
This is my profile.yaml file (I have cleaned it to remove what I deemed irrelevant, and tested this test-file):

```
version: "2"

profiles:

  root:
    password-file: "restic-encryption-password.txt"
    backup:
      use-fs-snapshot: true # Note that VSS Snapshot does not work on all remote drives, such as USB-sticks
      group-by: "host,tags"
      exclude-if-present: .nobackup-restic

      iexclude-file:
        - windows.exclude

      repository: "\\\\towerAdministrator\\windowsbackup\\Restic\\windows"

# Individual schedules work when this is included, inside this root.backup section:
      # schedule: daily #'*:00,30'
      # schedule-permission: system
      # schedule-priority: background
      # schedule-lock-mode: default
      # schedule-lock-wait: 215m30s
      # schedule-log: logs/profile-backup.log

# ----------

  drivec:
    inherit: root
    tag:
      - "C:\\"
    backup:
      schedule-log: logs/profile-drivec.log
      source:
        - "C:\\"


  drived:
    inherit: root
    tag:
      - "D:\\"
    backup:
      schedule-log: logs/profile-drived.log
      source:
        - "D:\\"

groups:
  maindrives:
    continue-on-error: true
    profiles:
      - drivec
      - drived
#      - development

schedules:
    full: # give a name to your schedule
        group: maindrives
        schedule:
            - "Mon..Fri *:00,15,30,45" # every 15 minutes on weekdays
        permission: system
        run: backup # backup is the default if not specified

```

#### Extra questions
I use inheritance, because I have not gotten mixins to work in v0.23. My root profiles also show up in the help overview `.\resticprofile.exe `. Is it possible to inform resticprofile that those are just for inheritance and should thus be ignored in help-overview and in `schedule --all` ? This does not matter much, but seems nice-to-have if using inheritance.

Would you prefer if I write stuff like this elsewhere, like on the restic-forum?
