### ISSUE TITLE
[bug] retention doesn't seem to honor host - incorrectly removes snapshot from another machine

### ISSUE THREAD

**Issue by thiscantbeserious** [creativeprojects/resticprofile#266]
I run restic currently on two machines - one of that is the "**backupserver**", another one is my "**cluster**".

**both do have a /boot volume - that I'm backing up.**

upon running

**`resticprofile boot.backup` on backupmaster removed a snapshot for the wrong host - cluster**:

```bash
remove 1 snapshots:
ID        Time                 Host        Tags                   Paths
-----------------------------------------------------------------------
03217116  2023-10-09 06:00:01  cluster      boot,files,unraid_usb  /boot
-----------------------------------------------------------------------
1 snapshots

keep 1 snapshots:
ID        Time                 Host        Tags                   Reasons           Paths
-----------------------------------------------------------------------------------------
a48ea50e  2023-10-09 10:19:06  backupserver         boot,files,unraid_usb  hourly snapshot   /boot
                                                                  daily snapshot
                                                                  weekly snapshot
                                                                  monthly snapshot
                                                                  yearly snapshot
-----------------------------------------------------------------------------------------
```

the profile looks like this on both machines (default is the repository and packsize nothing more):

```yaml
boot:
  inherit: default
  backup:
    verbose: true
    source:
      - /boot
    tag:
      - boot
      - files
      - unraid_usb
    schedule: "*-*-* *:00:00" #every full hour, from https://www.freedesktop.org/software/systemd/man/systemd.time.>
  retention:
    keep-daily: 7
    keep-hourly: 3
    keep-weekly: 4
    keep-monthly: 12
    keep-yearly: 3
    keep-tag: #keep all snapshots with these tags
      - forever
    after-backup: true
```

`resticprofile version 0.23.0 commit 1024189afa2ffc59f3bf1025db732b674988844c`

`restic 0.16.0 compiled with go1.20.6 on linux/amd64`
