### ISSUE TITLE
Hand made variables are defined even if commented out

### ISSUE THREAD

**Issue by Toizi** [creativeprojects/resticprofile#274]
When using [hand made variables](https://creativeprojects.github.io/resticprofile/configuration/variables/index.html#hand-made-variables), commenting out the declarations does not work.

Example `profiles.toml`:
```toml
version = "1"

# {{ $testing := "123"}}
[default]
  source = ["{{ $testing }}"]
```

```
$ resticprofle show
...
profile default:
    source:  123
```
