### ISSUE TITLE
HTTP hook Authorization header value is replaced in post requests

### ISSUE THREAD

**Issue by jkermes** [creativeprojects/resticprofile#326]
Hello
Authorization header value is replaced by value `×××` in POST requests when using HTTP hooks

here is my config
```
    [test.backup.send-finally]
      method = "POST"
      url = "https://someurl/api/v4/posts"
      body-template = "mattermost_body_template.json"

    [[test.backup.send-finally.headers]]
      name = "Content-Type"
      value = "application/json"

    [[test.backup.send-finally.headers]]
      name = "Authorization"
      value = "Bearer ****"
```
Is there a specific way to declare an authorization header to avoid this issue?

**Comment by Vatson112** [comment]
Can confirm:

Here is my config:

```toml
[notify-me.backup]
[[notify-me.backup.send-before]]
method = "POST"
url = "https://redacted"
body-template = "ntfy-backup-started.json"
[[notify-me.backup.send-before.headers]]
name = "Authorization"
value = "Bearer secret_token"
[[notify-me.backup.send-before.headers]]
name = "Content-Type"
value = "application/json"
```

Here is resticprofile logs:

```
2024/02/22 16:47:31 starting "send-before" from backup 1/1
2024/02/22 16:47:31 calling: POST "https://redacted"
Authorization:  ×××
Content-Type:   application/json
User-Agent:     resticprofile/0.26.0

2024/02/22 16:47:31 request body:
{
    "topic": "backup",
    "message": "Profile: caddy\nCommand: backup",
    "title": "Backup started",
    "tags": ["caddy"],
    "priority": 1
}

2024/02/22 16:47:31 "https://redacted" returned: 403 Forbidden
Alt-Svc:                      h3=":443"; ma=2592000
Content-Type:                 application/json
Date:                         Thu, 22 Feb 2024 13:47:31 GMT
Server:                       Caddy
Content-Length:               100
Access-Control-Allow-Origin:  *

2024/02/22 16:47:31 "send-before" returned an error: HTTP 403 Forbidden
```

Here is reverse proxy log:

```json
{"level":"error","ts":1708609395.1271415,"logger":"http.log.access.log1","msg":"handled request","request":{"remote_ip":"redacted","remote_port":"45486","client_ip":"redacted","proto":"HTTP/2.0","method":"POST","host":"redacted","uri":"/","headers":{"Content-Type":["application/json"],"User-Agent":["resticprofile/0.26.0"],"Content-Length":["149"],"Accept-Encoding":["gzip"],"Authorization":[]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"redacted"}},"bytes_read":149,"user_id":"","duration":0.004734385,"size":100,"status":403,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"],"Content-Type":["application/json"],"Date":["Thu, 22 Feb 2024 13:43:15 GMT"],"Content-Length":["100"],"Access-Control-Allow-Origin":["*"]}}
```

Authorization header is empty in reverse proxy logs.
