### ISSUE TITLE
Fatal: nothing to backup, please specify target files/dirs

### ISSUE THREAD

**Issue by WMP** [creativeprojects/resticprofile#34]
Hello, this is my config  on 0.11:
```
global:
    scheduler: crond

default:
  repository: "rest:http://.../srv2l/"
  password-file: "password.txt"
  initialize: false
  status-file: backup-status.json

  backup:
    verbose: true
    schedule-permission: system
    schedule-log: "profile-backup.log"
    schedule: 
      - "*-*-* 02:00:00"

  forget:
    before-backup: false
    after-backup: true
    keep-within: "3d"
    compact: false
    prune: true
    schedule-permission: system
    schedule-log: "profile-forget.log"
    schedule:
      - "*-*-* 06:00:00"
  
  check:
    read-data:  true
    # if scheduled, will check the repository the first day of each month at 3am
    schedule: "*-*-* 04:00:00"

sftp-callrecords:
  inherit: default
  backup:
    source:
      - "/var/lib/lxc/sftp/rootfs"

root:
  inherit: default
  backup:
    source:
      - /root
      - /etc
      
```
I  execute:
```
resticprofile schedule --all
```
and  this give me cron  configuration:
```
00 02 * * *     cd /root && /usr/local/bin/resticprofile --no-ansi --config /etc/resticprofile/profiles.yaml --name default --log profile-backup.log backup
00 04 * * *     cd /root && /usr/local/bin/resticprofile --no-ansi --config /etc/resticprofile/profiles.yaml --name default check
00 06 * * *     cd /root && /usr/local/bin/resticprofile --no-ansi --config /etc/resticprofile/profiles.yaml --name default --log profile-forget.log forget

```

But  in   _profile-backup.log_ i have:
```
2021/03/15 02:00:01 INFO  profile 'default': starting 'backup'
Fatal: nothing to backup, please specify target files/dirs
2021/03/15 02:00:01 ERROR backup on profile 'default': exit status 1
```

What i doing wrong in my configuration?
