### ISSUE TITLE
schedule-log log file is empty.

### ISSUE THREAD

**Issue by adilfulara** [creativeprojects/resticprofile#362]
With the following yaml set in the profile block
```yaml
default:
    backup:
        verbose: true
        schedule: daily
        schedule-log: '{{ tempFile "backup.log" }}'
        run-finally: 'cp {{ tempFile "backup.log" }} /home/adilfulara/restic-config/backup{{ .Now.Format "2006-01-02T15-04-05"}}.log'
        check-after: true
        check-before: true
        one-file-system: true
```

and running 
```zsh
$ restic version
restic 0.12.1 compiled with go1.18.1 on linux/amd64

$ resticprofile version
resticprofile version 0.26.0 commit 2ab1f3a38467114aeb4095c0924817b369280e39
```

The log lines do not get added to the file at scheduled run.
```zsh
ll backup*
-rw-r--r-- 1 adilfulara adilfulara 0 Apr  7 16:05 backup2024-04-07T16-05-47.log
-rw-r--r-- 1 adilfulara adilfulara 0 Apr  7 20:25 backup2024-04-07T20-25-45.log
-rw-r--r-- 1 adilfulara adilfulara 0 Apr  7 20:26 backup2024-04-07T20-26-24.log
-rw-r--r-- 1 adilfulara adilfulara 0 Apr  8 00:00 backup2024-04-08T00-00-04.log
```

When i running it ad-hoc, i see the log lines as expected on stdout.

The systemctl unit file is 
```zsh
cat /home/adilfulara/.config/systemd/user/resticprofile-backup@profile-default.timer
[Unit]
Description=backup timer for profile default in profiles.yaml

[Timer]
OnCalendar=daily
Unit=resticprofile-backup@profile-default.service
Persistent=true

[Install]
WantedBy=timers.target
```

What am i doing wrong for the log output to the file?
