### ISSUE TITLE
Feature request: Add support for nested hand-made variables

### ISSUE THREAD

**Issue by adamantike** [creativeprojects/resticprofile#363]
## Problem

Currently, hand-made variables do not support nesting, which sometimes helps to reduce duplication and simplify configuration files.

Here is a simple example, trying to reuse a single Healthchecks host URL across multiple projects:

```yaml
version: "1"

{{ $healthchecksURL := "https://healthchecks.com" }}
{{ $healthchecksURLProj1 := "{{ $healthchecksURL }}/ping/uuid1" }}
{{ $healthchecksURLProj2 := "{{ $healthchecksURL }}/ping/uuid2" }}

proj1:
  env:
    HEALTHCHECKS_URL: "{{ $healthchecksURLProj1 }}"

proj2:
  env:
    HEALTHCHECKS_URL: "{{ $healthchecksURLProj2 }}"
```

Running `show` indicates that no variable expansion was done when initializing `$healthchecksURLProj1`:

```shell
$ resticprofile -n proj1 show
global:
    ionice-class:             2
    default-command:          snapshots
    restic-arguments-filter:  true
    restic-lock-retry-after:  1m0s
    restic-stale-lock-age:    1h0m0s
    min-memory:               100
    send-timeout:             30s

profile proj1:
    prometheus-push-format:  text

    env:
        HEALTHCHECKS_URL:  {{ $healthchecksURL }}/ping/uuid1
```

## Proposed solution

* Include the variable expansion logic during hand-made variable initialization/assignment.
* If the nested variable hasn't been initialized yet, the program could fail to indicate a configuration error.
