### ISSUE TITLE
Security issue: RESTIC_PASSWORD and other envieonmant variables are available to every user in systemd service unit

### ISSUE THREAD

**Issue by Vanav** [creativeprojects/resticprofile#367]
If I install systemd service (`resticprofile schedule.schedule`) then every environment variable defined in config file is available for any user on server. Example:
`/etc/restic/profiles.yaml`:
```
default:
  env:
    RESTIC_REPOSITORY: 'rest:http://login:password@192.168.100.100:8000/project'
    RESTIC_PASSWORD: 'restic-pass'
schedule:
  inherit: default
...
```
