### ISSUE TITLE
Can't use groups of profiles - unknown command "backup_group" for "restic"

### ISSUE THREAD

**Issue by Tom5421** [creativeprojects/resticprofile#392]
Below is my config, I'm trying to setup and configure groups but the documentation is weak on this part and I'm not sure if I've misconfigured part of it. 

```
version: "1"

default:
  repository: "b2:my_repo_here"
  password-file: "repository-password"
  verbose: true

  env:
    B2_ACCOUNT_ID: "123"
    B2_ACCOUNT_KEY: "123"

  backup:
    source: ["/home", "/docker"]


groups:
  backup_group:
    - default
```
When I run resticprofile profiles I get this:
```
Profiles available (name, sections, description):
  default:  (backup)

Groups available (name, profiles, description):
  backup_group:  [default]
```
When I run `resticprofile backup_group` I get this:
`unknown command "backup_group" for "restic"`

Thanks
Tom
