### ISSUE TITLE
Fatal: create repository at b2:oc-restic-backup:evelyn/traefik failed: config already exists

### ISSUE THREAD

**Issue by xoxys** [creativeprojects/resticprofile#41]
Since the last update of resticprofile we see such messages in the logs and our cronjob is reporting these jobs as failed due to this error written to stderr. Is there a way to disable/ignore this particular error? While the message itself is valid, I don't really care about already existing config :)

**Comment by creativeprojects** [comment]
Hi,
Sorry about that. I haven't seen it in any of my backup, can you post an example of your configuration?

**Comment by xoxys** [comment]
Sure, no worries: 

```
---
global:
  default-command: "snapshots"
  initialize: true
  min-memory: 100

groups:
  full-backup:
  - traefik

default:
  cleanup-cache: true
  env:
    B2_ACCOUNT_ID: **SECRET**
    B2_ACCOUNT_KEY: **SECRET**
    RESTIC_PASSWORD: **SECRET**
  lock: /var/lock/restic/resticprofile.lock
  repository: b2:oc-restic-backup:evelyn
  retention:
    [...]

traefik:
  backup:
    check-before: true
    exclude-caches: true
    one-file-system: true
    source:
    - /etc/traefik
  inherit: default
  repository: b2:oc-restic-backup:evelyn/traefik
```
