### ISSUE TITLE
[question] step/one-by-one execution

### ISSUE THREAD

**Issue by DenisBY** [creativeprojects/resticprofile#411]
I couldn't find in documentation and issues how to execute commands one by one. I.e. I want to execute `backup`, then `forget` and then `prune`. How to achieve it?

**Comment by creativeprojects** [comment]
It's actually quite easy, you can make use of 2 flags on the `retention` target like so:

```yaml
profile:
  backup:
    source: ...
  retention:
    after-backup: true
    prune: true
```

- `after-backup: true` will run the `retention` target after the backup (which is running the `forget` command)
- `prune: true` will run the forget command with the `--prune` flag
