### ISSUE TITLE
HTTP Hooks debug

### ISSUE THREAD

**Issue by anshibanov** [creativeprojects/resticprofile#428]
I have this configuration on windows server:

```
kms:
    inherit: default-settings
    repository: "sftp:orange@hostbrr:/mnt/1tb/restic/rb-test"
    backup:
        source:
            - c:\kms
    send-after:
          - method: GET
            url: https://<uptime-kuma>/api/push/pTFxCh2scs?status=up&msg=%PROFILE_NAME%&ping=
    send-after-fail:
          - method: GET
            url: https://<uptime-kuma>/api/push/pTFxCh2scs?status=down&msg=%ERROR%&ping=
```
`<uptime-kuma>` - this is replaced url of my selfhosted instance uptime kuma

I want to debug the work of HTTP Hooks because I do not receive any data on the server side of pushes. I tried to run restik profile with the key --verbose 

`resticprofile.exe --verbose -n kms backup`

but did not receive information about sending pushes in the log :(

Is there a way to increase logging and see HTTP sending?
