### ISSUE TITLE
version 1 of groups no longer work with schedule in resticprofile 0.29.0

### ISSUE THREAD

**Issue by stucki-stuck** [creativeprojects/resticprofile#439]
Hello 

This code worked in version 0.28.1. It doesn't work anymore in `0.29.0`: 

```yaml
version: "1"

groups:
  all-backups:
    - nexus
...
```

l'erreur en version `0.29.0` : 
```bash
resticprofile --name all-backups schedule
2024/12/02 14:16:01 using configuration file: /etc/resticprofile/profiles.yaml
2024/12/02 14:16:01 no schedule found for profile 'all-backups'
```

this example is still in [the doc](https://creativeprojects.github.io/resticprofile/configuration/examples/index.html) : 
```yaml
# a group is a profile that will call all profiles one by one
groups:
  # when starting a backup on profile "full-backup",
  # it will run the "root" and "src" backup profiles
  full-backup:
    - root
    - src
```
It should be clarified whether this is a bug or a new feature in the way groups are written, in which case the documentation should be updated with the new procedure.
