### ISSUE TITLE
Avoid putting S3 credentials on disk

### ISSUE THREAD

**Issue by danlamanna** [creativeprojects/resticprofile#443]
Is there a way to avoid writing credentials for S3 backends to a file?

I'd really like to use the bitwarden CLI (or even the keyring command) to fetch my credentials directly so I don't need to put things like `AWS_SECRET_ACCESS_KEY` on disk.

Is something like this possible:

```toml
[default]
   repository = "..."
    
   run-before = 'export AWS_SECRET_ACCESS_KEY=$(bw get ...)'

   # or, some command that sets env vars to be picked up by restic
   env-command = "..."
```
