### ISSUE TITLE
Retention not respected? (no forget / prune after period)

### ISSUE THREAD

**Issue by elegos** [creativeprojects/resticprofile#446]
Hello everyone.

I've used the configuration v2 to setup my restic profile. In particular I have 2 folders that need backup, with different retention policies. An extract of the configuration follows.

```yaml
groups:
  full:
    profiles:
      - minecraft
      - immich
    continue-on-error: true
    schedules:
      backup:
        after-network-online: true
        at: '03:00'
        permission: 'system'

profiles:
  default:
    repository: "local:/var/backups/helium"
    password-file: "/var/backups/helium.key"

  minecraft:
    inherit: default

    # ...

    retention:
      before-backup: false
      after-backup: true

      keep_daily: 4
      keep_weekly: 0
      keep_monthly: 0

      forget: true
      prune: true

  immich:
    inherit: default

    # ...

    retention:
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 3

      forget: true
      prune: true
```

This is the list of snapshots I have:

```
ID        Time                 Host        Tags        Paths
-------------------------------------------------------------------------------------
30568635  2024-12-08 15:30:53  helium                  /home/gfurlan/docker/minecraft
0217d33a  2024-12-08 16:42:34  helium                  /home/gfurlan/docker/immich
cb26a17c  2024-12-08 17:03:53  helium                  /home/gfurlan/docker/immich
538c22cb  2024-12-08 17:05:04  helium                  /home/gfurlan/docker/minecraft
f00ab26f  2024-12-08 17:05:07  helium                  /home/gfurlan/docker/immich
1c9324f5  2024-12-09 18:40:56  helium                  /home/gfurlan/docker/minecraft
cac1bc88  2024-12-09 18:40:59  helium                  /home/gfurlan/docker/immich
f9c7daf5  2024-12-09 22:55:08  helium                  /home/gfurlan/docker/minecraft
866196d7  2024-12-09 22:55:11  helium                  /home/gfurlan/docker/immich
ee7c8182  2024-12-10 03:00:49  helium                  /home/gfurlan/docker/minecraft
452eddde  2024-12-10 03:00:52  helium                  /home/gfurlan/docker/immich
f299229b  2024-12-11 03:00:49  helium                  /home/gfurlan/docker/minecraft
612ac61e  2024-12-11 03:00:52  helium                  /home/gfurlan/docker/immich
e1eb4d40  2024-12-12 03:00:49  helium                  /home/gfurlan/docker/minecraft
9a7e4d07  2024-12-12 03:00:52  helium                  /home/gfurlan/docker/immich
0b87ec6e  2024-12-13 03:00:49  helium                  /home/gfurlan/docker/minecraft
0f3a5b45  2024-12-13 03:00:52  helium                  /home/gfurlan/docker/immich
ebe8915f  2024-12-14 03:00:49  helium                  /home/gfurlan/docker/minecraft
19a00b87  2024-12-14 03:00:52  helium                  /home/gfurlan/docker/immich
edb54dc6  2024-12-15 03:00:49  helium                  /home/gfurlan/docker/minecraft
d3634ec8  2024-12-15 03:00:52  helium                  /home/gfurlan/docker/immich
7d298e74  2024-12-16 03:00:25  helium                  /home/gfurlan/docker/minecraft
1190c82e  2024-12-16 03:00:27  helium                  /home/gfurlan/docker/immich
c4a8c1d5  2024-12-17 03:00:25  helium                  /home/gfurlan/docker/minecraft
6d16d435  2024-12-17 03:00:27  helium                  /home/gfurlan/docker/immich
3178d0c4  2024-12-18 03:00:19  helium                  /home/gfurlan/docker/minecraft
e58f14cd  2024-12-18 03:00:23  helium                  /home/gfurlan/docker/immich
bbf62437  2024-12-19 03:00:19  helium                  /home/gfurlan/docker/minecraft
295fef74  2024-12-19 03:00:22  helium                  /home/gfurlan/docker/immich
2c3f7733  2024-12-20 03:00:19  helium                  /home/gfurlan/docker/minecraft
67846b43  2024-12-20 03:00:22  helium                  /home/gfurlan/docker/immich
4f231ba3  2024-12-21 03:00:19  helium                  /home/gfurlan/docker/minecraft
3972c864  2024-12-21 03:00:22  helium                  /home/gfurlan/docker/immich
-------------------------------------------------------------------------------------
```

I expected to only have 4 Minecraft's snapshots, but I see 16 of them. Also the immich's backups should be less (7 dailies, 2 weeklies, 0 monthly (so far)).

Have I misunderstood how to configure retention policies?

Thanks

**Comment by elegos** [comment]
From a fast review of the code, it seems that `profile.retention` has been deprecated, and it is suggested to use `profile.forget`. I'm surprised that a deprecated section is still not used in any case, though after setting up the `forget` section and running resticprofile with the forget command (i.e. `resticprofile --config /var/backups/helium.resticprofile.yml --profile minecraft forget`, it removed the old backups.

I'm keeping the issue open until tomorrow, i.e. the next backup & forget nightly schedule.

**Comment by elegos** [comment]
The schedule still "forgot" to forget and prune the old backups...

This is the service generated by resticprofile:

```
[Unit]
Description=resticprofile backup for profile full in ./helium.resticprofile.yml
After=network-online.target

[Service]
Type=notify
WorkingDirectory=/var/backups
ExecStart=/bin/resticprofile --no-prio --no-ansi --config ./helium.resticprofile.yml run-schedule backup@full
Environment="RESTICPROFILE_SCHEDULE_ID=./helium.resticprofile.yml:backup@full"
Environment="HOME=/root"
Environment="SUDO_USER=gfurlan"
```

I tried to add also forget@full (manually trying `sudo resticprofile --no-prio --no-ansi --dry-run --config ./helium.resticprofile.yml run-schedule backup@full forget@full`), but the dry-run didn't write about the forget step.

Am I missing anything?

**Comment by creativeprojects** [comment]
Sorry I missed this thread during my Christmas break 😬 

**The retention section itself is not deprecated.** What is deprecated is the way to schedule the retention alone, like:

```yaml
profile:
  backup:
    schedule: ...
  retention:
    schedule: ...
```

There's no reason why the `retention` and `forget` section should behave differently.

You can check the exact Restic command by specifying the `-v` (or `--verbose`) flag.

So you can run the schedule manually:
```
/bin/resticprofile --config ./helium.resticprofile.yml --verbose run-schedule backup@full
```

From there it should never easier to guess what is missing.

**Comment by jardleex** [comment]
Hi there,
please check your `source` definitions. I had a similar behavior and with `--verbose` I saw that resticprofiles passed the paths given in `source` 1:1 to restic. This only gave this output where nothing was set to forget.

~~~bash
repository 42599a6b opened (version 2, compression level auto)                                                                                                                                                     
Applying Policy: keep 5 daily, 3 weekly, 3 monthly snapshots and all snapshots with tags [[keep]]  
~~~

I had to **remove the trailing slash** in my source definitions to be equal with the output of `resticprofile $profile.snapshots` where no trailing slashes are visible.
After that the `restic forget command worked properly and so will the `retention` do.

**Comment by elegos** [comment]
I've managed to handle backup + forget "consecutively" (15 minutes are just fine in this case) via the following group:

```yaml
groups:
  full:
    profiles:
      - immich
      - gitlab
      - vikunja
      - minecraft
      - foundryvtt
    continue-on-error: true
    schedules:
      backup:
        after-network-online: true
        at: '03:00'
        permission: 'system'
      forget:
        after-network-online: true
        at: '03:15'
        permission: 'system'
```

And then scheduling the "full" group.
