### ISSUE TITLE
Clarification backup: source/exclude paths

### ISSUE THREAD

**Issue by dpantel** [creativeprojects/resticprofile#447]
Hey there. Just wanted a clarification for this: if a backup declares a source directory/file that is inside an excluded directory, does it get backed up? Example follows...

```
backup:
   source:
      - /home
      - /home/dave/daves-not-here-man
   exclude:
      - /home/dave
```
