### ISSUE TITLE
[feature] make 'check' run by 'backup' configurable  

### ISSUE THREAD

**Issue by seternate** [creativeprojects/resticprofile#450]
Hi there,

I hope I did not overlooked any documentation or any thread on the forum, but I have a use-case here. Please refer me or/and reject if so.

I want to have a check run on each repo without "--read-data" flag after each backup to ensure integrity of that backup. Easy said easy done, just add the "check-after". But I also want to run the check once a week with the "--read-data" flag enabled to ensure integrity, but since it is heavy and takes quite a while I want to run it just weekly.
Problem now is, if I configure the "check" with "read-data: true" and schedule it to run every week, the check run by the "backup" also runs with "read-data" flag. 

It would be cool to be able to either configure multiple check sections with different schedules to run one without "read-data" flag and one with the flag or the ability to configure the check run by "backup" to not use the "read-data" flag.

Current config:
```yaml
version: "1"

global:
  scheduler: crond

default:
  repository: "local:/backup"
  password-file: "/password"

  backup:
    schedule: daily
    check-after: true
    source:
      - "/source"

  check:
    schedule: weekly
    read-data: true
```

Example of possible config:
```yaml
version: "1"

global:
  scheduler: crond

default:
  repository: "local:/backup"
  password-file: "/password"

  backup:
    schedule: daily
    check-after:
      read-data: false
    source:
      - "/source"

  check:
    schedule: weekly
    read-data: true
```

**Comment by creativeprojects** [comment]
I see what you mean.
It might not be the prettiest but you can easily achieve this by using two profiles:

```yaml
version: "1"

global:
  scheduler: crond

default:
  repository: "local:/backup"
  password-file: "/password"

  backup:
    schedule: daily
    check-after: true
    source:
      - "/source"
  
  check:
    read-data: false

weekly-check:
  inherit: default
  check:
    schedule: weekly
    read-data: true
```

(The check section in the `default` is not really needed by it helps remembering what it does when you come back to it later 😆)
