### ISSUE TITLE
group profiles__APPEND/PREPEND not working?

### ISSUE THREAD

**Issue by andreymal** [creativeprojects/resticprofile#454]
I'm trying to use config v2 to split my profiles into multiple files and combine them to one group using `profiles__APPEND`. A simplified example of what I'm trying to do:

```yaml
# profiles.yaml
version: "2"

groups:
  all:
    profiles:
      - profile1

includes:
  - profile*.yaml

profiles:
  profile1: {backup: {source: .}}
```

```yaml
# profile2.yaml
version: "2"

groups:
  all:
    profiles__APPEND:
      - profile2

profiles:
  profile2: {backup: {source: .}}
```

According to [the JSON schema](https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json), both files are valid and `profiles__APPEND` is a valid key.

However:

```
$ resticprofile profiles
2025/01/21 21:23:00 using configuration file: profiles.yaml

Profiles available (name, sections, description):
  profile1:  (backup)  
  profile2:  (backup)  

Groups available (name, profiles, description):
  all:  [profile1]
```

`profile2` is present but not added to the `all` group.

I tried different versions back to 0.16.1 but this configuration doesn't work with any version I tested.

Is this even supposed to work? Or is this just a mistake in the JSON schema?
