### ISSUE TITLE
prometheus-labels not being pushed to the prometheus push gateway or to the generated prometheus file.

### ISSUE THREAD

**Issue by jaepetto** [creativeprojects/resticprofile#463]
I have a resticprofile that is pretty straightforward:

```yaml
version: "1"

global:
  default-command: snapshots
  initialize: false
  priority: low

default:
  repository: '*****'
  password-file: '/root/*****'
  env:
    AWS_ACCESS_KEY_ID: "*****"
    AWS_SECRET_ACCESS_KEY: "*****"
  prometheus-save-to-file: "/var/log/resticprofile.prom"
  prometheus-push: "http://localhost:9091/"


  backup:
    initialize: false
    verbose: true
    exclude-caches: true
    source:
      - /data
    tag:
      - backend
    host: ic-registry.epfl.ch
    check-after: true
    no-error-on-warning: true
    schedule: daily
    schedule-priority: background
    schedule-permission: system
    schedule-lock-wait: 2h
    schedule-log: /var/log/resticprofile-backup-schedule.log
    extended-status: true
    prometheus-labels:
      - host: {{ .Hostname }}
      - app: 'registry'
      - component: 'backend'

  forget:
    prune: true
    keep-last: 30
    schedule: "05:00"
    schedule-permission: system
    schedule-lock-wait: 2h
    schedule-log: /var/log/resticprofile-forget-schedule.log

  check:
    read-data: false
    schedule: "06:00"
    schedule-permission: system
    schedule-lock-wait: 2h
    schedule-log: /var/log/resticprofile-check-schedule.log
```

For some reason, the tags (`host`, `app` and `component`) are not showing up on the prometheus push gateway or in the generated prometheus file (`/var/log/resticprofile.prom`).

Aren't they supposed to show up on the prometheus push gateway or in the generated prometheus file ?
