### ISSUE TITLE
how to config restic params like rclone.args?

### ISSUE THREAD

**Issue by ar0c** [creativeprojects/resticprofile#487]
i'd like to config a profile like `restic -o rclone.args="serve restic --stdio --b2-hard-delete --multi-thread-streams 0" -o rclone.timeout=0 -r rclone:a:quark_bak -v backup ~/photo/camera/ --tag photo --tag camera `
i try to config like this, which i got in https://github.com/creativeprojects/resticprofile/issues/80#issuecomment-953308614:
```yaml
version: "1"
base:
  repository: "rclone:a:quark_bak"
  password-file: "password.txt"
  rclone:
    program: /usr/bin/local/rclone
    stdio: true
    bwlimit: 1M
    b2-hard-delete: true
    multi-thread-streams: 0
    timeout: 0
  backup:
   exclude:
     - "immich"
     - "*eaDir*"
     - "#recycle"
```
but seems not work
run command `resticprofile --dry-run -n base backup`
returns `dry-run: /usr/bin/restic backup --exclude=immich --exclude="*eaDir*" --exclude=#recycle --password-file=password.txt --repo=rclone:a:quark_bak --tag=mt --tag=photo --verbose=1 /root/photo/mt/`
 how should do this?

**Comment by creativeprojects** [comment]
This is a nice way of doing it for sure, but it has never been implemented.

For now you need to specify the full option as a string.

So your configuration should look like this:

```yaml
version: "1"
base:
  repository: "rclone:a:quark_bak"
  password-file: "password.txt"
  option:
    - rclone.args="serve restic --stdio --b2-hard-delete --multi-thread-streams 0"
    - rclone.timeout=0
  backup:
   exclude:
     - "immich"
     - "*eaDir*"
     - "#recycle"

```

**Comment by rktjmp** [comment]
Just a note for fellow travelers, I had to do something slightly different, when using rclone for append only via ssh authorized_keys when using `resticprofile 0.32.0`.

I could not use double quotes in the options array and had to separate the `rclone.program` from `rclone.args`.

```
# ssh/authorized_keys on the server
restrict,command="rclone serve restic --stdio --append-only backups/..path-to-repo" ssh-ed25519 AAAAC3....
```
```yaml
# restic profile

version: "1"

global:
  restic-binary: "/Users/user/.bin/restic"

default:
  repository: "rclone:"
  option:
    - rclone.program='ssh'
    - rclone.args='rsync.net'
  password-file: "password.txt"
  backup:
    verbose: true
    source:
      - "/Users/user/..."
```

*With double quotes, I'd get errors like this:*
```
invalid argument "rclone.program=\"ssh\"" for "-o, --option" flag: parse error on line 1, column 16: bare " in non-quoted-field
```

*Without separating the exec and host, I'd get this error:*
```
fatal: unable to open repository at rclone:: cmd.Start: exec: "ssh rsync.net": executable file not found in $PATH
```

From the CLI, `restic -o rclone.program="ssh host"` works, and is normally what people suggest, if actually a bit sloppy, it has to be a bit different in the config file.

Edit: Looking at `resticprofile -v` we can see the command output, and why  maybe things don't work the same:

`resticprofile` seems to escape spaces in the option, and escaping the quotes: `--option=rclone.program=\"ssh\ rsync.net\"`.
