### ISSUE TITLE
Schedule command hard-codes version number when resticprofile is installed via Homebrew

### ISSUE THREAD

**Issue by joeacarstairs** [creativeprojects/resticprofile#490]
My unit files in `/etc/systemd/system` generated by `resticprofile schedule` are hard-coding the version number into the path to the resticprofile binary. This means that when I upgrade resticprofile, the unit files will break. (I think this might have happened to me recently - I wanted to do a full backup and my schedules hadn't ran successfully for four months! Thankfully I had another means of recovering my data in that case :relieved:)

## Steps to reproduce

1. `brew install resticprofile --with-restic`
2. Write a backup profile in a `profiles.toml` (an excerpt from mine is below)
3. `sudo /home/linuxbrew/.linuxbrew/bin/resticprofile -c /path/to/profiles.toml schedule --all`
4. `cat /etc/systemd/system/resticprofile-backup@profile-default.service`

Expected: `ExecStart=/home/linuxbrew/.linuxbrew/bin/resticprofile`
Actual: `ExecStart=/home/linuxbrew/.linuxbrew/Cellar/resticprofile/0.30.0/bin/resticprofile`

<details><summary>profiles.toml (excerpt)</summary>
```toml
version = "1"

[global]
  restic-binary = "/home/linuxbrew/.linuxbrew/bin/restic"
  log = "/home/joeac/log/resticprofile/resticprofile.log"

[default]
  description                   = "Back up user data, application data and system config to BackBlazeB2 S3 Bucket"
  env-file                      = ".env"
  repository                    = "s3:s3.eu-central-003.backblazeb2.com/<my bucket ID>/repo"
  schedule-after-network-online = true
  password-command              = "secret-tool lookup key <my repo secret key>"

  [default.backup]
    check-after                            = true
    check-before                           = true
    schedule                               = "daily"
    schedule-after-network-online          = true
    schedule-lock-wait                     = "2h"
    schedule-log                           = "/home/joeac/log/resticprofile/do-joeac-personal-backup-schedule.log"
    schedule-permission                    = "system"
    schedule-priority                      = "background"
    source                                 = [
      "/etc/systemd/system",
      "/home",
    ]
```
</details>
