### ISSUE TITLE
schedule creates multiple timers

### ISSUE THREAD

**Issue by saviodsouza** [creativeprojects/resticprofile#494]
Hi,

I am using resticprofile version 'resticprofile version 0.30.0 commit aab1a70d8db21f041299ad9a8d5b69ee98f3b4ae' with 'restic 0.18.0 compiled with go1.24.1 on linux/amd64'

The command `resticprofile schedule --all` creates multiple timmers when there are multiple profiles with inherites.
By default 1 timmer for the default profile where all paremetes are set like passwords, repository, etc. The rest of them for each addon profile with inherit defined.

```
default:
  run-before: 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND"'
  run-after: 'echo "== run-after profile $PROFILE_NAME and command $PROFILE_COMMAND"'
  run-after-fail: 'echo "== ERROR in profile $PROFILE_NAME command ${PROFILE_COMMAND}: $ERROR_MESSAGE"'
  run-finally: 'echo "== run-finally from profile $PROFILE_NAME after command $PROFILE_COMMAND"'
  description: '{{ .Hostname }} discription......'
  status-file: '{{ .ConfigDir }}/status/status-{{ .Profile.Name }}_{{ .Now.Format "2006-01-02 15:04 IST" }}.json'
  force-inactive-lock: false
  env-file:
    - '{{ .ConfigDir }}/keyfiles/env/od.env' # rclone env
  password-file: '{{ .ConfigDir }}/path.key'
  repository-file: '{{ .ConfigDir }}/path....'
  compression: "xxxxx"
  pack_size: xxx
  read-concurrency: xxx
  init:
    copy-chunker-params: true
    from-repository: '{{ .ConfigDir }}/from.repo'
    from-password-file: '{{ .ConfigDir }}/from.key'
  copy:
    run-before: 'echo "== run-before Copy repository $PROFILE_NAME to SP-Servers"'
    extended-status: true
    repository-file: '{{ .ConfigDir }}/repo.file'
    password-file: '{{ .ConfigDir }}/key.file'
    schedule-permission: user
    schedule-log: '{{ .ConfigDir }}/logs/copy/{{ .Profile.Name }}_{{ .Now.Format "2006 Jan 02 15:04 IST" }}.log'
    schedule: "*-*-* 07:30:00"
  ........................
  .........................
  ..............
  ```
  
  sources.yaml
  
  ```
  groups:
  myhosts_backups:
    - logs
    - resticprofile



logs:
  inherit: default
  initialize: false
  lock: /tmp/resticprofile-logs.lock
  description: '{{ .Hostname }} restic logs'
  backup:
    exclude-caches: true
    source:
      - "{{ .Env.HOME }}/logs"
    tag:
      - logs
    no-error-on-warning: false
  snapshots:
    host: '{{ .Hostname }}'
    path: "{{ .Env.HOME }}/logs"
    tag:
      - logs
  restore:
    host: '{{ .Hostname }}'
    target: "{{ .Env.HOME }}/logs"
    verify: true


resticprofile:
  inherit: default
  initialize: false
  lock: /tmp/resticprofile.lock
  description: '{{ .Hostname }} resticprofile'
  backup:
    exclude-caches: true
    source:
      - "{{ .ConfigDir }}"
    tag:
      - resticprofile
    no-error-on-warning: false
  snapshots:
    host: '{{ .Hostname }}'
    path: "{{ .ConfigDir }}"
    tag:
      - resticprofile
  restore:
    host: '{{ .Hostname }}'
    target: "{{ .ConfigDir }}"
    verify: true
    
```
    
    
The above creates 3 timmers
``` 
# resticprofile unschedule --all
Removed "/etc/systemd/system/timers.target.wants/resticprofile-check@profile-default.timer".
Removed "/etc/systemd/system/timers.target.wants/resticprofile-check@profile-logs.timer".
Removed "/etc/systemd/system/timers.target.wants/resticprofile-check@profile-resticprofile.timer".
Removed "/etc/systemd/system/timers.target.wants/resticprofile-copy@profile-default.timer".
Removed "/etc/systemd/system/timers.target.wants/resticprofile-copy@profile-logs.timer".
Removed "/etc/systemd/system/timers.target.wants/resticprofile-copy@profile-resticprofile.timer".
```

This further creates 3 snapshots on the remote with resticprofile default.copy..... as all 3 timers are triggered.

Is this a Bug?

Regards,
Savio D'souza.
