### ISSUE TITLE
run: does not work for check

### ISSUE THREAD

**Issue by saviodsouza** [creativeprojects/resticprofile#496]
Hii,

Here is a snippet of the yaml config

Below are 2 outputs of check and stats. For some reason run-xxx works correctly as expected. 
check the run-xxxx does not execute where as it works for stats, snapshots.

```
---

version: "1"

default:
  run-before:
    - 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND @ {{ .Hostname }}"'
    - 'mkdir -p {{ .ConfigDir }}/logs/{{ .Profile.Name }}/{{ .Now.Format "2006-01-02" }}'
  run-after: 'echo "== run-after profile $PROFILE_NAME and command $PROFILE_COMMAND"'
  run-after-fail: 'echo "== ERROR in profile $PROFILE_NAME command ${PROFILE_COMMAND}: $ERROR_MESSAGE"'
  run-finally: 'echo "== run-finally from profile $PROFILE_NAME after command $PROFILE_COMMAND"'
  description: 'Discription'
  status-file: '{{ .ConfigDir }}/.......json'
  force-inactive-lock: false
  env-file:
    - '{{ .ConfigDir }}.........env' # env
  password-file: '{{ .ConfigDir }}......
  repository-file: '{{ .ConfigDir }}......'
  compression: "max"
  pack_size: 64
  read-concurrency: 8
  .....
  .....
  .....
  .....
  check:
    run-before: 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after: 'echo "== run-after profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after-fail: 'echo "== ERROR in profile $PROFILE_NAME command ${PROFILE_COMMAND}: $ERROR_MESSAGE"'
    run-finally:
      - 'echo "== run-finally from profile $PROFILE_NAME after command $PROFILE_COMMAND"'
      - 'sleep 5'
      - 'bash "$HOME/bin/alert.sh" "Restic $PROFILE_NAME {{ .Hostname }} $PROFILE_COMMAND" "$PROFILE_COMMAND on $PROFILE_NAME @ {{ .Hostname }}" {{ tempFile "resticprofile.log" }}'
      - 'cp {{ tempFile "resticprofile.log" }} {{ .ConfigDir }}/logs/{{ .Profile.Name }}/{{ .Now.Format "2006-01-02" }}/{{ .Now.Format "2006-01-02_15:04" }}.log'
    extended-status: true
    read-data: false
    schedule-permission: user
    schedule-log: '{{ .ConfigDir }}/logs/check/{{ .Profile.Name }}_{{ .Now.Format "2006 Jan 02 15:04 IST" }}.log'
    status-file: '{{ .ConfigDir }}/status/status-{{ .Profile.Name }}-check-{{ .Now.Format "2006 Jan 02 15:04 IST" }}.json'
    schedule: "*-*-* 15:15:00"
  stats:
    run-before: 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after: 'echo "== run-after profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after-fail: 'echo "== ERROR in profile $PROFILE_NAME command ${PROFILE_COMMAND}: $ERROR_MESSAGE"'
    run-finally:
      - 'echo "== run-finally from profile $PROFILE_NAME after command $PROFILE_COMMAND"'
      - 'sleep 5'
      - 'bash "$HOME/bin/alert.sh" "Restic $PROFILE_NAME {{ .Hostname }} $PROFILE_COMMAND" "$PROFILE_COMMAND on $PROFILE_NAME @ {{ .Hostname }}" {{ tempFile "resticprofile.log" }}'
      - 'cp {{ tempFile "resticprofile.log" }} {{ .ConfigDir }}/logs/{{ .Profile.Name }}/{{ .Now.Format "2006-01-02" }}/{{ .Now.Format "2006-01-02_15:04" }}.log'
    mode: raw-data
  ...
  ...
  ...
  snapshots:
    run-before: 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after: 'echo "== run-after profile $PROFILE_NAME and command $PROFILE_COMMAND"'
    run-after-fail: 'echo "== ERROR in profile $PROFILE_NAME command ${PROFILE_COMMAND}: $ERROR_MESSAGE"'
    run-finally:
      - 'echo "== run-finally from profile $PROFILE_NAME after command $PROFILE_COMMAND"'
      - 'sleep 5'
      - 'bash "$HOME/bin/alert.sh" "Restic $PROFILE_NAME {{ .Hostname }} $PROFILE_COMMAND" "$PROFILE_COMMAND on $PROFILE_NAME @ {{ .Hostname }}" {{ tempFile "resticprofile.log" }}'
      - 'cp {{ tempFile "resticprofile.log" }} {{ .ConfigDir }}/logs/{{ .Profile.Name }}/{{ .Now.Format "2006-01-02" }}/{{ .Now.Format "2006-01-02_15:04" }}.log'
    compact: false
    extended-status: true
    status-file: '{{ .ConfigDir }}/status/status-{{ .Profile.Name }}-check-{{ .Now.Format "2006 Jan 02 15:04 IST" }}.json'
    schedule-log: '{{ .ConfigDir }}/logs/snapshots/{{ .Profile.Name }}_{{ .Now.Format "2006 Jan 02 15:04 IST" }}.log'


```

Output .....

```
resticprofile default.check
== run-before profile default and command check @ hostname
using temporary cache in /tmp/restic-check-xxxxx
create exclusive lock for repository
load indexes
check all packs
xxxxxx
xxxxxx
check snapshots, trees and blobs
[x:xx] 100.00%  xxx / xxx snapshots
no errors were found
== run-after profile default and command check
== run-finally from profile default after command check
```

```
resticprofile default.stats
== run-before profile default and command stats @ hostname
== run-before profile default and command stats
scanning...
Stats in raw-data mode:
     Snapshots processed:  xxx
        Total Blob Count:  xxxxxx
 Total Uncompressed Size:  xxx.xxx GiB
              Total Size:  xxx.xxx GiB
    Compression Progress:  xxx.xx%
       Compression Ratio:  xx.xxx
Compression Space Saving:  xx.xx%
== run-after profile default and command stats
== run-after profile default and command stats
== run-finally from profile default after command stats
bash .... xx xx:xx:xx xxxxxxx  Email.......... Email was sent successfully!
== run-finally from profile default after command stats
```

resticprofile 30 and restic 18

Thank you
