### ISSUE TITLE
YAML help - quotes and environment variables in run-after-fail healthchecks curl URL

### ISSUE THREAD

**Issue by fmoledina** [creativeprojects/resticprofile#59]
I'm looking for some yaml help for the `run-after-fail` block of my resticprofile config. Upon failure, I'd like to send the exit code and the $ERROR_STDERR content to healthchecks.io using `curl`. See the below snippet.

```yaml
b2-backups:
  backup:
    ...
    run-before:
      - "docker stop my_container"
    run-after:  
      - "curl -fsS --retry 3 https://hc-ping.com/uuid"
      - "docker start my_container"
  run-after-fail:
    - "curl -fsS --retry 3 --data-raw '$ERROR_STDERR' https://hc-ping.com/uuid/$ERROR_EXIT_CODE"
    - "docker start my_container"
```

With that `curl` line, the exit code populates fine, but the `--data-raw` literally populates _$ERROR_STDERR_ in the request body. When I replace `--data-raw '$ERROR_STDERR'` with `--data-raw '{{ .Env.ERROR_STDERR }}'`, the request body instead says _\<no data\>_.

What's the correct way to include the environment variables in the `curl` line item using a config file in YAML format?

Thank you.

**Comment by creativeprojects** [comment]
Hi,

1. The `--data-raw '{{ .Env.ERROR_STDERR }}'` cannot work because the `.Env.ERROR_STDERR` variable is expanded when resticprofile **reads** the configuration file and the variable doesn't exist at that point, restic hasn't started yet.

2. At a glance, I would say that `'$ERROR_STDERR'` doesn't work is because a parameter in single quote is sent *as is* on the command line. What *should* work (I haven't tested it though) is using double quotes instead.

For more information about quotes: https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

Can you try like that?

``` yaml
b2-backups:
  backup:
    ...
    run-before:
      - "docker stop my_container"
    run-after:  
      - "curl -fsS --retry 3 https://hc-ping.com/uuid"
      - "docker start my_container"
  run-after-fail:
    - "curl -fsS --retry 3 --data-raw \"$ERROR_STDERR\" https://hc-ping.com/uuid/$ERROR_EXIT_CODE"
    - "docker start my_container"
```
