### ISSUE TITLE
Add configuration variable to pass custom restic flags

### ISSUE THREAD

**Issue by bartgenuit** [creativeprojects/resticprofile#61]
Hi, thanks for this awesome piece of software. It makes managing my restic backups so much smoother.
I am trying to put backups directly into S3 Intelligent Tiering (using `-o s3.storage-class`), but my backups are scheduled using resticprofile, so it would be a bit of a pain adding this flag manually to each systemd service definition.

So, would it be possible to have an `other` variable in the profiles.yaml where you can specify a string containing flags that just gets appended to the restic call?
```
[default.backup]
exclude-file = "excludes"
exclude-caches = true
source = [ "/", "/var" ]
other = "-o s3.storage-class=INTELLIGENT_TIERING"
```

**Comment by creativeprojects** [comment]
Actually it already exists, there's an example here: https://github.com/creativeprojects/resticprofile#simple-toml-configuration

```toml
[default.backup]
exclude-file = "excludes"
exclude-caches = true
source = [ "/", "/var" ]
option = "s3.storage-class=INTELLIGENT_TIERING"
```
