### ISSUE TITLE
Schedule in docket container

### ISSUE THREAD

**Issue by cheesemarathon** [creativeprojects/resticprofile#74]
I have resticprofile running using the docker container. Backup works fine and I have a schedule set but once the backup has completed the container stops so the next scheduled back won't run. Am I doing something wrong or does the schedule not work with the docker container?

**Comment by creativeprojects** [comment]
Are you using a scheduler *inside* the container? if it's the case, that can't work because the container gets destroyed after running. But then I'm also surprised that the container can be started doing nothing and waiting for a scheduled job 🤔

**Comment by cheesemarathon** [comment]
Hi Yes I was trying to use the scheduler in the docker container but clearly it doesn't work. It just runs the backup then the container stops. That's not a problem though I'll just use my host system to schedule the container to run. My current WIP profile for reference


```
default:
  repository: "s3:http://X.X.X
X:9768/XXX"

  env:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    RESTIC_PASSWORD: ""

  backup:
    schedule: "*-*-* 00:00:00"
    verbose: true
    source:
    - "/mnt/appdata"

  retention:
    after-backup: true
    before-backup: false
    compact: false
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 12
    keep-yearly: 5
    prune: true
```

**Comment by bdillahu** [comment]
I was looking at going down this same route - any thoughts about a "long running" docker container that has all the scheduling, etc. capabilities? Or is there a negative to doing that?

**Comment by jkellerer** [comment]
Without having it tried, scheduling may work with the default alpine based container when you start `crond` after creating the schedules with `resticprofile`. Requires that you ensure `profiles.(yaml|conf)` sets `crond` [as scheduler](https://github.com/creativeprojects/resticprofile#scheduled-backups).

E.g. with `docker-compose.yaml` (untested):

```yaml
version: '2'

services:
  scheduled-backup:
    image: creativeprojects/resticprofile
    entrypoint: "/bin/sh"
    command:
      - "-c"
      - "resticprofile schedule --all && crond -f -l 8"
```

**Comment by KreativeKrise** [comment]
I have modified it a little bit, so that changes on the profile are also detected.

docker-compose.yml
```
version: '2'

services:
  scheduled-backup:
    image: creativeprojects/resticprofile
    entrypoint: '/bin/sh'
    command:
      - '-c'
      - 'crond && resticprofile-schedule.sh && inotifyd resticprofile-schedule.sh /etc/resticprofile:w'
    volumes:
      - './profiles.yaml:/etc/resticprofile/profiles.yaml:ro'
      - './resticprofile-schedule.sh:/usr/local/bin/resticprofile-schedule.sh:ro'
      - ...
```

resticprofile-schedule.sh:
```
#!/bin/sh

resticprofile schedule --all
```
