### ISSUE TITLE
Few enhancements

### ISSUE THREAD

**Issue by renard** [creativeprojects/resticprofile#8]
I'am glad to see the progresses of this project, especially the go rewrite.

Here are some thoughts to make this project even better:

* Configuration file should be searched within standard config paths such as `~/.config/resticprofile/profiles.yml` instead of current directory.

* I use a different directory for each profile in `~/.config/resticprofile/<PROFILE>/`. In my `profiles.yml` file I have:

```yml
profile1:
  repository: 'rclone:'
  option:
    - "rclone.program=ssh -F /Users/me/.config/resticprofile/profile1/sshconfig restic"
  password-file: profile1/password
  backup:
    exclude-file: profile1/exclude-files
    files-from: profile1/files-from
    host: profile1
```

It would be great to have variable expansion to something like:

```yml
profile1:
  repository: 'rclone:'
  option:
    - "rclone.program=ssh -F /Users/me/.config/resticprofile/{{ .name }}/sshconfig restic"
  password-file: {{ .name }}/password
  backup:
    exclude-file: {{ .name }}/exclude-files
    files-from: {{ .name }}/files-from
    host: {{ .name }}
```

Where `{{ .name }}` would be replaced by `profile`. This would make each profile configuration very simple and reusable and allow profile factorisation.

Thanks.

**Comment by creativeprojects** [comment]
>     * Configuration file should be searched within standard config paths such as `~/.config/resticprofile/profiles.yml` instead of current directory.

Actually this is now the case, thanks to this PR: https://github.com/creativeprojects/resticprofile/pull/5
You can try to move them and they should be picked up automatically

 
> Where `{{ .name }}` would be replaced by `profile`. This would make each profile configuration very simple and reusable and allow profile factorisation.

I was thinking about it the other day while I started working on HCL configuration files. That could be interesting...

**Comment by creativeprojects** [comment]
> It would be great to have variable expansion to something like:
> 
> ```yaml
> profile1:
>   repository: 'rclone:'
>   option:
>     - "rclone.program=ssh -F /Users/me/.config/resticprofile/{{ .name }}/sshconfig restic"
>   password-file: {{ .name }}/password
>   backup:
>     exclude-file: {{ .name }}/exclude-files
>     files-from: {{ .name }}/files-from
>     host: {{ .name }}
> ```
> 
> Where `{{ .name }}` would be replaced by `profile`. This would make each profile configuration very simple and reusable and allow profile factorisation.

I would see something more like that:

```yaml
template:
  repository: 'rclone:'
  option:
    - "rclone.program=ssh -F /Users/me/.config/resticprofile/{{ .Profile.Name }}/sshconfig restic"
  password-file: {{ .Profile.Name }}/password
  backup:
    exclude-file: {{ .Profile.Name }}/exclude-files
    files-from: {{ .Profile.Name }}/files-from
    host: {{ .Profile.Name }}

profile1:
  inherit: template

```

**Comment by renard** [comment]
Yes this is a nice way to do it.

Regarding the default configuration file I saw some weird thing happening. I'll try to have a look this week.

Feel free to split this issue if it's easier for you to handle.

**Comment by creativeprojects** [comment]
> Regarding the default configuration file I saw some weird thing happening. I'll try to have a look this week.

This is very possible, I've gone trough a fair amount of refactoring around the configuration files recently. I'm tempted to ditch the viper library and deal with loading all different kinds of configuration myself

**Comment by creativeprojects** [comment]
@renard I'm back on it after a little break.

Right now I have it working with this sample configuration:

```yaml
src:
    lock: "$HOME/resticprofile-profile-{{ .Profile.Name }}.lock"
    backup:
        check-before: true
        exclude:
        - /**/.git
        exclude-caches: true
        one-file-system: false
        run-after: echo All Done!
        run-before:
        - "echo Hello {{ .Env.LOGNAME }}"
        - "echo current dir {{ .CurrentDir }}"
        - "echo config dir {{ .ConfigDir }}"
        - "echo profile started at {{ .Now }}"
        source:
        - "{{ .Env.HOME }}/go/src"
        tag:
        - "{{ .Profile.Name }}"
        - dev
    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        keep-within: 30d
        prune: true
    snapshots:
        tag:
        - "{{ .Profile.Name }}"
        - dev
```


The list of available variables is:
- .Profile.Name
- .Now
- .CurrentDir
- .ConfigDir
- .Env.{NAME}

(It's easy to add more variables if needed)

It works with profile inheritance (like mentioned before)

Each flag is isolated into its own environment (go template). So you can't put a block of flags inside a `if` or some other fancy things like that. Having one template for the whole configuration would require rewriting the configuration loader 😄 I could change my mind if there's a need for it though

**Comment by creativeprojects** [comment]
I knew I could do better 😄 

Now you can do all sort of fancy things like a proper Go template:

```yaml
# yaml configuration file is not well suited for nested templates as it requires the exact number of spaces
# also if you redefine an existing block it replaces the previous definition
{{ define "tags" }}
        tag:
        - "{{ .Profile.Name }}"
        - dev
{{ end }}
---
generic:
    password-file: "{{ .ConfigDir }}/{{ .Profile.Name }}-key"
    repository: "/backup/{{ .Now.Weekday }}"
    lock: "$HOME/resticprofile-profile-{{ .Profile.Name }}.lock"
    initialize: true

    backup:
        check-before: true
        exclude:
        - /**/.git
        exclude-caches: true
        one-file-system: false
        run-after: echo All Done!
        run-before:
        - "echo Hello {{ .Env.LOGNAME }}"
        - "echo current dir: {{ .CurrentDir }}"
        - "echo config dir: {{ .ConfigDir }}"
        - "echo profile started at {{ .Now.Format "02 Jan 06 15:04 MST" }}"
        {{ template "tags" . }}

    retention:
        after-backup: true
        before-backup: false
        compact: false
        keep-within: 30d
        prune: true
        {{ template "tags" . }}

    snapshots:
        {{ template "tags" . }}

src:
    inherit: generic
    backup:
        source:
        - "{{ .Env.HOME }}/go/src"

```
