### ISSUE TITLE
[proposal] Improved configuration file format

### ISSUE THREAD

**Issue by creativeprojects** [creativeprojects/resticprofile#80]
# Proposal for an updated configuration file format

## Introduction

The current file format was decided at the time resticprofile was only using the `toml` format. Nesting pieces of configuration in blocks is not the easiest as you have to specify the whole path in the block:

```toml
[profile]

[profile.backup]
...

```

Since then, I believe the `yaml` format is preferred over `toml`.

My proposal is to make a `version 2` of the configuration file, the current file format is `version 1`.

**Both formats will continue to be valid** (like `docker-compose`):

- if no version is specified, the `version 1` is used. This is the current format
- if a version is specified (`2`) the new format will be expected

## New format availability

The new format `version 2` will be available for:
- TOML
- YAML
- JSON

**It won't be available for HCL**. This may not be definitive, but it's not widely used and it's becoming more and more difficult to support HCL.

**HCL can still be used as is, `version = 1`**

## New format specifications

I will show the specification using the `yaml` as examples, because it's probably the most readable format.

### version

```yaml
---
version: 2
```

### global

The global section does not change. We'll keep all the global configuration in there.

```yaml
---
global:
    default-command: snapshots
    initialize: false
    priority: low

```

### profiles

All your profiles will be nested under a `profiles` section. Please note the schedules are no longer described inside the profile, but in a separate section `schedules` (see following sections).

```yaml
profiles:
    default:
        env:
            tmp: /tmp
        password-file: key
        repository: /backup

    documents:
        inherit: default
        backup:
            source: ~/Documents
        snapshots:
            tag:
                - documents
```

### groups

The list of profiles will be nested under a `profiles` section, so we can add more configuration to groups later.

```yaml
groups:
    full: # name of your group
        profiles:
            - root
            - documents
            - mysql
```

This format leaves more space for improvements later (like a `repos` section maybe?)

Does that make sense to you?

Please reply in this issue, thanks :)

*Edit*:
- changed numbering as such: `1` is current and `2` is the new format
- HCL not supported with version 2
- `schedules` section removed

**Comment by creativeprojects** [comment]
As a matter of fact, this is the reason why I need to modernise the configuration, to allow for a `targets` section 😛 

(I think you should be able to update the Wiki now?)

**Comment by jkellerer** [comment]
Yes it works. Try to contribute asap.

**Comment by creativeprojects** [comment]
Using go templates is a bit cumbersome, specially for non developers who never used a similar templating language...

I was thinking about something that we could introduce in the config version 2: templates. Basically they would work like building blocks that you can assemble together.

``` yaml
templates:
  backup:
    source: /

  target:
    repository: /backup

profiles:
  backup_target:
    templates:
      - target
      - backup
```

and that will assemble both templates to generate the profile. We could also introduce variables (although we have to decide on a syntax for the variables)

``` yaml
templates:
  healthchecks:
    send-before:
        method: HEAD
        url: {URL}/start

    send-after:
        method: HEAD
        url: {URL}

    send-after-fail:
        method: POST
        url: {URL}/fail
        body: "${ERROR}\n\n${ERROR_STDERR}"
        headers:
          - name: Content-Type
            value: "text/plain; charset=UTF-8"

profiles:
  with_monitoring:
    backup: /
    templates:
      - name: healthchecks
        vars:
          URL: https://hc-ping/uuid
```

**Comment by jkellerer** [comment]
Config templates is a missing bit, go-templates is more like macros, it has its use case but it generates markup not a parsed config and this makes it less easy to use. 

The proposed syntax looks good to me. If implemented on top of the viper API, it could use `viper.MergeConfigMap` which would automatically handle list and map merging. Since templates have a deterministic order (like includes) this means one could control how properties are merged (or replaced when not a list or map).

Had tried to implement proper list merging for inheritance (using "propertyName+" added to plain "propertyName") but this is not so easy as it sounds as it must happen after inheritance and also recursively up to the parent. Templates would also allow to extend lists but in a much simpler way.

Still have the test implementation around on top of the viper API could dump it into a branch and turn it into processing templates instead, shall I?

**Comment by jkellerer** [comment]
Made a quick working prototype and found that `viper.MergeConfigMap` does actually replace slices not merging them (not sure why I thought it would, looks like I had looked at the wrong things when I tested includes...).

Besides this it works quite well with little code to add.

**Comment by creativeprojects** [comment]
> Besides this it works quite well with little code to add.

That's good news 😉 

I quite like how this new configuration is opening new possibilities. Now I need to go back to it and finish refactoring the scheduling (that was the last part not working in v2 if I remember well)

Also I'm thinking if there's an easy way we could allow both configurations to be valid...

```yaml

# simple syntax
profiles:
  with_monitoring:
    backup: /
    templates:
      - healthchecks

# full syntax
  with_monitoring:
    backup: /
    templates:
      healthchecks:
        replace: true
        vars:
          URL:  https://hc-ping/uuid
```

**Comment by jkellerer** [comment]
That's how the prototype implements it :) .. simple and full syntax

**Comment by creativeprojects** [comment]
> That's how the prototype implements it :) .. simple and full syntax (can even be mixed in the same list)

Doh! sorry I should have checked first 😊

**Comment by jkellerer** [comment]
Variables might need an option to define defaults though. Maybe something the unix shell would also support "${var:-default}".

**Comment by creativeprojects** [comment]
Good point, that's a nice to have as well 👍🏻

**Comment by darkmattercoder** [comment]
I am confused. Is the version 2 already fully implemented and ready to use? The docs seem a bit vague about whether it is still only a proposal.

**Comment by sedlund** [comment]
I've been using v2 of the format, and noticed the `scedules:` format in the docs, and tried it out, but it seems like its not implemented yet?

**Comment by jkellerer** [comment]
@creativeprojects , this is a followup on the discussion started in #290, regarding the direction of schedules in V2. I made a comparison on the 2 options:

**Option 1**: current proposal with separate V2 schedules section in YAML and TOML:

```yaml
profiles:
  default:
    backup:
      schedule: "10:00,14:00,18:00,22:00"
      schedule-log: tcp://localhost:514

schedules:
  weekly-check:
    schedule: weekly
    profiles: "*"
    run: check
    log: tcp://localhost:514
```

```toml
[profiles.default.backup]
schedule = "10:00,14:00,18:00,22:00"
schedule-log = "tcp://localhost:514"

[schedules.weekly-check]
schedule = "weekly"
profiles = "*"
run = "check"
log = "tcp://localhost:514"
```

```
resticprofile schedule weekly-check default
```

**Option 2**: discussion in #290 with unified schedule section and schedules in V2 groups in YAML and TOML:

```yaml
version: "2"

profiles:
  default:
    backup:
      schedule: 
        at: "10:00,14:00,18:00,22:00"
        log: tcp://localhost:514

groups:
  all:
    profiles: "*"
    schedules:
      check:        
        at: weekly
        log: tcp://localhost:514
```

```toml
[profiles.default.backup.schedule]
at = ["10:00,14:00,18:00,22:00"]
log = "tcp://localhost:514"

[groups.all]
profiles = "*"

[groups.all.schedules.check]
at = "weekly"
log = "tcp://localhost:514"
```

Note: The current syntax for scheduling remains valid and transparently translates to 
 the new `Schedule` instance. It both are set, the settings would be merged.

```
resticprofile schedule default all

maybe:
resticprofile schedule all.check and/or check@all
resticprofile schedule default.backup and/or backup@default
```
