### ISSUE TITLE
Question about retention

### ISSUE THREAD

**Issue by megamorf** [creativeprojects/resticprofile#85]
Hey, first of all thanks for developing resticprofile. I've been running it for a while but just recently checked my snapshots and was a bit confused. Maybe you can explain what's going on. Here's my setup:

```
$ resticprofile version
resticprofile version 0.15.0 commit "8e7cf44c0d6775602ab0ce3412cd3d981ef543e5"
$ restic version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
``` 

**profiles.toml**

```toml
[groups]
apps = ["mayan", "spotifyreleasechecker", "wallabag", "wekan", "usrlocalbin"]

[default]
repository = "/opt/backups"
password-file = "key"
initialize = true
run-before = "echo Started!"
run-after = "echo Finished!"
run-after-fail = "echo An error occured!"
cache-dir = "/tmp/.restic"

[default.backup]
exclude-caches = true
one-file-system = true

[default.retention]
keep-daily = 14
keep-weekly = 4
keep-monthly = 12
keep-yearly = 2
keep-tag = [ "forever" ]
host = true

[mayan]
inherit = "default"
initialize = true

[mayan.snapshots]
tag = [ "{{ .Profile.Name }}" ]

[mayan.backup]
run-before = [
    "echo 'Backing up mayan'",
    "cd /home/megamorf/projects/mayan && docker-compose stop app",
    "cd /home/megamorf/projects/mayan && docker-compose exec -u postgres -T postgresql sh -c 'pg_dump -U $POSTGRES_USER -d $POSTGRES_DB --clean --no-owner --format=custom' > ./data/postgres-backup/$(date +%d-%m-%Y'_'%H_%M_%S).dump",
]
run-after = [
    "cd /home/megamorf/projects/mayan && docker-compose start app",
    "echo 'Finished mayan backup'",
]
exclude = [
    "/home/megamorf/projects/mayan/data/postgres",
    "/home/megamorf/projects/mayan/data/rabbitmq",
]
tag = [ "{{ .Profile.Name }}" ]
source = [ "/home/megamorf/projects/mayan" ]
check-before = true

[mayan.retention]
tag = [ "{{ .Profile.Name }}" ]


[spotifyreleasechecker]
inherit = "default"
initialize = true

[spotifyreleasechecker.snapshots]
tag = [ "{{ .Profile.Name }}" ]

[spotifyreleasechecker.backup]
run-before = [
    "echo 'Backing up spotifyreleasechecker'",
    "cd /home/megamorf/projects/SpotifyReleaseChecker && docker-compose stop release_checker",
]
run-after = [
    "cd /home/megamorf/projects/SpotifyReleaseChecker && docker-compose start release_checker",
    "echo 'Finished spotifyreleasechecker backup'",
]
exclude = []
tag = [ "{{ .Profile.Name }}" ]
source = [ "/home/megamorf/projects/SpotifyReleaseChecker" ]
check-before = true

[spotifyreleasechecker.retention]
tag = [ "{{ .Profile.Name }}" ]


[wekan]
inherit = "default"
initialize = true

[wekan.snapshots]
tag = [ "{{ .Profile.Name }}" ]

[wekan.backup]
run-before = [
    "echo 'Backing up wekan'",
    "cd /home/megamorf/projects/wekan && ./backup.sh",
]
run-after = [
    "echo 'Finished wekan backup'",
]
exclude = []
tag = [ "{{ .Profile.Name }}" ]
source = [ "/home/megamorf/projects/wekan" ]
check-before = true

[wekan.retention]
tag = [ "{{ .Profile.Name }}" ]


[wallabag]
inherit = "default"
initialize = true

[wallabag.snapshots]
tag = [ "{{ .Profile.Name }}" ]

[wallabag.backup]
run-before = [
    "echo 'Backing up wallabag'",
    "cd /home/megamorf/projects/wallabag && docker-compose stop wallabag",
    "cd /home/megamorf/projects/wallabag && ./backup.sh"
]
run-after = [
    "cd /home/megamorf/projects/wallabag && docker-compose start wallabag",
    "echo 'Finished wallabag backup'",
]
exclude = [
    "/home/megamorf/projects/wallabag/data/mysql*"
]
tag = [ "{{ .Profile.Name }}" ]
source = [ "/home/megamorf/projects/wallabag" ]
check-before = true

[wallabag.retention]
tag = [ "{{ .Profile.Name }}" ]


[usrlocalbin]
inherit = "default"
initialize = true

[usrlocalbin.snapshots]
tag = [ "{{ .Profile.Name }}" ]

[usrlocalbin.backup]
run-before = [
    "echo 'Backing up /usr/local/bin/'",
]
run-after = [
    "echo 'Finished /usr/local/bin backup'",
]
exclude = []
tag = [ "{{ .Profile.Name }}" ]
source = [ "/usr/local/bin" ]

[usrlocalbin.retention]
tag = [ "{{ .Profile.Name }}" ]
```

Resticprofile is run daily via cron:

```sh
# view with: journalctl -t resticprofile
resticprofile -c /home/megamorf/projects/restic/profiles.toml -n apps backup 2>&1 | systemd-cat -t resticprofile
```

Now when I check the snapshots the retention does not seem to get applied:

```plaintext
resticprofile -c /home/megamorf/projects/restic/profiles.toml -n mayan snapshots
Started!
2021/12/01 01:45:13 profile 'mayan': initializing repository (if not existing)
2021/12/01 01:45:14 profile 'mayan': starting 'snapshots'
repository c46ae18f opened successfully, password is correct
ID        Time                 Host        Tags        Paths
------------------------------------------------------------------------------------
a2a3208b  2021-09-02 06:25:11  srvapp001   mayan       /home/megamorf/projects/mayan
2a160c50  2021-09-03 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
d0214f31  2021-09-04 06:25:26  srvapp001   mayan       /home/megamorf/projects/mayan
f6982b90  2021-09-05 06:25:20  srvapp001   mayan       /home/megamorf/projects/mayan
9585b002  2021-09-06 06:25:15  srvapp001   mayan       /home/megamorf/projects/mayan
03845fd1  2021-09-07 06:25:12  srvapp001   mayan       /home/megamorf/projects/mayan
1c5dbb53  2021-09-08 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
c25b0b30  2021-09-09 06:25:19  srvapp001   mayan       /home/megamorf/projects/mayan
4dfb5df2  2021-09-10 06:25:29  srvapp001   mayan       /home/megamorf/projects/mayan
77868946  2021-09-11 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
def11675  2021-09-12 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
2e6903b1  2021-09-13 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
8f1e5824  2021-09-14 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
a707edf5  2021-09-15 06:25:14  srvapp001   mayan       /home/megamorf/projects/mayan
850a8651  2021-09-16 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
771d29ef  2021-09-17 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
ff3fb458  2021-09-18 06:25:29  srvapp001   mayan       /home/megamorf/projects/mayan
3d820eea  2021-09-19 06:25:15  srvapp001   mayan       /home/megamorf/projects/mayan
d27ec6bd  2021-09-20 06:25:23  srvapp001   mayan       /home/megamorf/projects/mayan
48fdec57  2021-09-21 06:25:24  srvapp001   mayan       /home/megamorf/projects/mayan
bd3042ee  2021-09-22 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
5c60203e  2021-09-23 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
75cc7bbf  2021-09-24 06:25:12  srvapp001   mayan       /home/megamorf/projects/mayan
b7b7b3af  2021-09-25 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
f585ba72  2021-09-26 06:25:24  srvapp001   mayan       /home/megamorf/projects/mayan
82b7e2d6  2021-09-27 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
9ae32c3f  2021-09-28 06:25:26  srvapp001   mayan       /home/megamorf/projects/mayan
36ef683f  2021-09-29 06:25:23  srvapp001   mayan       /home/megamorf/projects/mayan
19ce5c80  2021-09-30 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
c25fb006  2021-10-01 06:25:09  srvapp001   mayan       /home/megamorf/projects/mayan
e613432b  2021-10-02 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
814409af  2021-10-03 06:25:09  srvapp001   mayan       /home/megamorf/projects/mayan
37168df7  2021-10-04 06:25:09  srvapp001   mayan       /home/megamorf/projects/mayan
09b7f782  2021-10-05 06:25:10  srvapp001   mayan       /home/megamorf/projects/mayan
e89294a9  2021-10-06 06:25:11  srvapp001   mayan       /home/megamorf/projects/mayan
bda06273  2021-10-07 06:25:13  srvapp001   mayan       /home/megamorf/projects/mayan
21acc7ad  2021-10-08 06:25:17  srvapp001   mayan       /home/megamorf/projects/mayan
a4edae85  2021-10-09 06:25:17  srvapp001   mayan       /home/megamorf/projects/mayan
32436962  2021-10-10 06:25:12  srvapp001   mayan       /home/megamorf/projects/mayan
3fd4e44c  2021-10-11 06:25:13  srvapp001   mayan       /home/megamorf/projects/mayan
de269bd9  2021-10-12 06:25:24  srvapp001   mayan       /home/megamorf/projects/mayan
726772ea  2021-10-13 06:25:21  srvapp001   mayan       /home/megamorf/projects/mayan
76e184f3  2021-10-14 06:25:26  srvapp001   mayan       /home/megamorf/projects/mayan
073a6ec4  2021-10-15 06:25:12  srvapp001   mayan       /home/megamorf/projects/mayan
a3e6c6da  2021-10-16 06:25:10  srvapp001   mayan       /home/megamorf/projects/mayan
b58b0fca  2021-10-17 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
f791e840  2021-10-18 06:25:29  srvapp001   mayan       /home/megamorf/projects/mayan
2d785a02  2021-10-19 06:25:23  srvapp001   mayan       /home/megamorf/projects/mayan
3aee43ad  2021-10-20 06:25:13  srvapp001   mayan       /home/megamorf/projects/mayan
ec9faf23  2021-10-21 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
79b34ca9  2021-10-22 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
bf1d4d29  2021-10-23 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
3b86ad35  2021-10-24 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
2ee04eaf  2021-10-25 06:25:20  srvapp001   mayan       /home/megamorf/projects/mayan
61b52c75  2021-10-26 06:25:11  srvapp001   mayan       /home/megamorf/projects/mayan
cfccbb2e  2021-10-27 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
e8913fa1  2021-10-28 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
dd17dfd9  2021-10-29 06:25:10  srvapp001   mayan       /home/megamorf/projects/mayan
c6cf9b8b  2021-10-30 06:25:11  srvapp001   mayan       /home/megamorf/projects/mayan
ddf2fa28  2021-10-31 06:25:25  srvapp001   mayan       /home/megamorf/projects/mayan
03f0dcdb  2021-11-01 06:25:26  srvapp001   mayan       /home/megamorf/projects/mayan
f5984e8d  2021-11-02 06:25:17  srvapp001   mayan       /home/megamorf/projects/mayan
9fabf555  2021-11-03 06:25:12  srvapp001   mayan       /home/megamorf/projects/mayan
70db40bc  2021-11-04 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
031bd37c  2021-11-05 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
902a767e  2021-11-06 06:25:30  srvapp001   mayan       /home/megamorf/projects/mayan
43a114f2  2021-11-07 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
6babb144  2021-11-08 06:25:19  srvapp001   mayan       /home/megamorf/projects/mayan
a1d787ba  2021-11-09 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
34c1976e  2021-11-10 06:25:13  srvapp001   mayan       /home/megamorf/projects/mayan
609fd2aa  2021-11-11 06:25:31  srvapp001   mayan       /home/megamorf/projects/mayan
4275aab2  2021-11-12 06:25:09  srvapp001   mayan       /home/megamorf/projects/mayan
9c664ef8  2021-11-13 06:25:16  srvapp001   mayan       /home/megamorf/projects/mayan
7a682dc9  2021-11-14 06:25:10  srvapp001   mayan       /home/megamorf/projects/mayan
1c6353b3  2021-11-15 06:25:15  srvapp001   mayan       /home/megamorf/projects/mayan
e94eafc8  2021-11-16 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
2481c17a  2021-11-17 06:25:27  srvapp001   mayan       /home/megamorf/projects/mayan
2001daf7  2021-11-18 06:25:10  srvapp001   mayan       /home/megamorf/projects/mayan
6c589f10  2021-11-19 06:25:25  srvapp001   mayan       /home/megamorf/projects/mayan
aade799c  2021-11-20 06:25:25  srvapp001   mayan       /home/megamorf/projects/mayan
3598d62c  2021-11-21 06:25:27  srvapp001   mayan       /home/megamorf/projects/mayan
7da5f9c4  2021-11-22 06:25:27  srvapp001   mayan       /home/megamorf/projects/mayan
a6adb42b  2021-11-23 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
c7cecd49  2021-11-24 06:25:26  srvapp001   mayan       /home/megamorf/projects/mayan
08824849  2021-11-25 06:25:27  srvapp001   mayan       /home/megamorf/projects/mayan
cd4b63a8  2021-11-26 06:25:11  srvapp001   mayan       /home/megamorf/projects/mayan
9e2ae6c6  2021-11-27 06:25:17  srvapp001   mayan       /home/megamorf/projects/mayan
046d68ff  2021-11-28 06:25:22  srvapp001   mayan       /home/megamorf/projects/mayan
62608199  2021-11-29 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
bd07527a  2021-11-30 06:25:28  srvapp001   mayan       /home/megamorf/projects/mayan
------------------------------------------------------------------------------------
90 snapshots
2021/12/01 01:45:14 profile 'mayan': finished 'snapshots'
Finished!
``` 

Could you point out what's wrong and how the retention and forget sections are supposed to be used and how the compact and before/after-backup options affect the process.

Thanks in advance. Looking forward to your answer :-)
