### ISSUE TITLE
copy cmd has no lock-file

### ISSUE THREAD

**Issue by chymian** [creativeprojects/resticprofile#97]
during a copy run, there is no lock-file generated for that repo. is that on purpose?
which could maybe lead to a backup & prune operation while a copy is already running. that seems like  a potential for corrupting the remote repo?

also there needs to be a `schedule` entry in the copy-section of the profile that the cmd. works at all.

**Comment by creativeprojects** [comment]
1. Do you mean a _resticprofile_ lock file or a _restic_ lock file?

As far as _resticprofile_ is concerned, there's no separate lock file for the second repository, but the profile lock file is still used.

```yaml
profile:
    repository: "/backup/original"
    password-file: key
    lock: "/backup/resticprofile.lock"
    copy:
        repository: "/backup/copy"
        password-file: other_key
```

In such a configuration, the lock file `/backup/resticprofile.lock` will be used for any command in the profile (`snapshots`, `backup`, `check`, `copy`, etc.)

2. I don't understand what you're asking about `schedule`: yes there's a `schedule` section on the `copy` command, if it's what you're asking
